### ISSUE TITLE
mycloud

### ISSUE THREAD

**Issue by crak3rjack** [Gujal00/ResolveURL#105]
@Gujal00 Im getting this error and thanks!
https://pastebin.com/jkRf0WSq

**Comment by Gujal00** [comment]
Log snippets aren't helpful. Need full debug log to see what is happening with what versions calling each other

**Comment by crak3rjack** [comment]
@Gujal00 Hope this helps!
http://pastebin.com/Tds9QuqJ

**Comment by Gujal00** [comment]
As I snippets are no good, need full debug log. But there is small clue there that you are on version 5.1.66 of ResolveURL yet using newer plugins which is the issue.
The latest versions are 
ResolveURL 5.1.67
xxx Plugins 2.1.23

These two work together and are not compatible if versions mismatch. Upgrade to the latest ResolveURL and it will work

Also the mcloud link you are using for testing is the resolved url already and not the actual embed and will not play through link tester

**Comment by crak3rjack** [comment]
@Gujal00 I have the repository but it won't update to 5.1.67... where can I get the zip and thanks.

**Comment by shellc0de27** [comment]
@Gujal00 Can confirm this resolver is broken at the moment. Looks like maybe they changed yesterday or so, cause was working great a couple days ago.
Besides the vizcloud domain needing to be updated they are now maybe obfuscating the media_id when we call `https://{host}/info/{media_id}`.

Here is my source for these so you can see what im talking about:
`aHR0cHM6Ly9mbW92aWVzLnRvLw==`

**Comment by Gujal00** [comment]
> @Gujal00 I have the repository but it won't update to 5.1.67... where can I get the zip and thanks.

The [repository zip is here](https://github.com/Gujal00/smrzips/blob/master/zips/repository.resolveurl/repository.resolveurl-1.0.0.zip)

The release zips are always here
```
https://github.com/Gujal00/smrzips/tree/master/zips/script.module.resolveurl
```

**Comment by mbebe** [comment]
@Gujal00  please take a look. I did it in my addon - media_id is obfuscated and base64 encoded with custom letters.
[vidcloud_deco.txt](https://github.com/Gujal00/ResolveURL/files/8748381/vidcloud_deco.txt)

**Comment by Gujal00** [comment]
I spent a while going through the obfuscated yesterday and had the completed the code almost :-)
```
_0x597deb = this['m']('LCbu3iYC7ln24K7P', _0x597deb),
var _0x1c9411 = '0wMrYU+ixjJ4QdzgfN2HlyIVAt3sBOZnCT9Lm7uFDovkb/EaKpRWhqXS5168ePcG'
```
Thanks for your code. Will combine yours with mine to get a compact one and will add to ResolveURL

**Comment by shellc0de27** [comment]
@mbebe @Gujal00 
Thank you both :)

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/84a2597cf16985b1e1c3236b53a915d147840dc4

**Comment by gloriosotv** [comment]
Amigo atualize o addon do f4mtester e o proxy igual que voce fez no addon plugin.video.live.streamspro.zip

Friend, update the f4mtester addon and the proxy just like you did in the plugin.video.live.streamspro.zip

**Comment by doko-desuka** [comment]
FMovies (the only website where mcloud.to was present, probably owned by them too along with Vidplay) is probably down for good. For many weeks the website didn't update with new content, and now it's offline for days.  

So this resolver is likely not needed anymore.
