### ISSUE TITLE
VOE Domain

### ISSUE THREAD

**Issue by Nagirah90** [Gujal00/ResolveURL#106]
Please change voesx.py to

`name = "Voe"`
 `domains = ["voe.sx", "voe-unblock.com", "voe-unblock.net", "voeunblock.com"]`
 `pattern = r'(?://|\.)(voe(?:-unblock|unblock)?\.(?:sx|com|net))/(?:e/)?([0-9A-Za-z]+)'`

Thank you!

**Comment by Gujal00** [comment]
Added, Thanks
