### ISSUE TITLE
streamlare.py

### ISSUE THREAD

**Issue by lavara123** [Gujal00/ResolveURL#114]
there is a problem

`https: //streamlare.com/e/10rwmD79yy1lRaZ8`

**Comment by Gujal00** [comment]
Server is slow, I dont see a problem in resolveurl, it is resolving correctly

**Comment by lavara123** [comment]
@Gujal00 
The link I gave leads to slmaxed.com.
If it redirects to slmaxed.com the api link doesn't seem to work ie:

```
https://streamlare.com/api/video/download/get
https://streamlare.com/api/video/stream/get
```

I guess the host of the api links should also change when there is a redirect.

**Comment by lavara123** [comment]
@Gujal00 

https://streamlare.com/e/Xvb6NnJqBYNlPOkZ

and the json name returned in this link is '1080p' not 'file'

**Comment by Gujal00** [comment]
> @Gujal00 The link I gave leads to slmaxed.com. If it redirects to slmaxed.com the api link doesn't seem to work ie:
> 
> ```
> https://streamlare.com/api/video/download/get
> https://streamlare.com/api/video/stream/get
> ```
> 
> I guess the host of the api links should also change when there is a redirect.
Don't see a need for it as it the link works in smr link tester. Currently it is not opening the embed url at all so wouldn't know if there is a redirect. doing so will cause one additional call regardless of redirect. Shouldnt be a problem. WIll code it if absolutely required

> `https: //streamlare.com/e/Xvb6NnJqBYNlPOkZ`
> and the json name returned in this link is '1080p' not 'file'
The current code looks for 'file' or 'Original'. This embed doesnt seem to have either. Will code a fix for such embeds, Thanks

**Comment by lavara123** [comment]
@Gujal00 thank you 👍
