### ISSUE TITLE
Xvideos new domain

### ISSUE THREAD

**Issue by imurreflection** [Gujal00/ResolveURL#144]
Hi, it appears that xvideos is using another domain. 

https://in.xvideos1.mx/

Can you include this in resolve url?

**Comment by imurreflection** [comment]
I tried working on this so i modified smr and included this url and installed it. Secondly, i modified xvideos.py in cumination. Though, after installation, i was able to see listing along with thumbnails, the videos still do not play. What else needed to be done?

**Comment by Gujal00** [comment]
.mx uses different logic and may need its own plugin separate from the current xvideos plugin
