### ISSUE TITLE
Real Debrid - no (re)authorize option

### ISSUE THREAD

**Issue by colharris113** [Gujal00/ResolveURL#145]
In the Universal Resolvers 2 -> Real Debrid section I no longer have the "(re)Authorize" option.  

Using the latest version (.71) on Kodi.

**Comment by Gujal00** [comment]
Check if ResolveURL origin repo is ResolveURL Repository. If it is not take the issue to the repository provider. 
![Image1](https://i.imgur.com/lEzmFMy.png)
The module from this repo has the option showing correctly
![Image 2](https://i.imgur.com/ybgwmXo.png)

**Comment by colharris113** [comment]
The module is from the correct repo.  The option is still missing.
![IMG_20220630_085846_580](https://user-images.githubusercontent.com/87669967/176624608-db1ecdca-0c10-4722-8b01-c449103e048a.jpg)
![IMG_20220630_085831_316](https://user-images.githubusercontent.com/87669967/176624615-aa8c59fa-70ef-46a5-83e3-36a5f0923807.jpg)

**Comment by Gujal00** [comment]
May be a skin issue, can you switch to the default estuary skin temporarily to see if the option shows?

**Comment by colharris113** [comment]
Spot on it was the skin.  Thanks for replying.

**Comment by Gujal00** [comment]
@colharris113 just noticed that the RealDebrid priority is set to 100 on your screenshot. You need to drop it to 90 or lower if you want ResolveURL to prefer RD for supported hosters instead of ResolveURL native plugins
