### ISSUE TITLE
Do you have gdriveplayer.to?

### ISSUE THREAD

**Issue by lavara123** [Gujal00/ResolveURL#151]
it would be nice if added.

base url:
`https://gdriveplayer.to/`

test url:
```https://gdriveplayer.to/embed.php?hash=IwyOTa8wCwJQfbtOTp0CfQyb3x2wLl3Zk395pGOc69YOo5PryYBNLu16/Cu1mU0pLwE+YV3nlCQNwj7vwmGevjLZjqduZR6kj641327GDLS29hBvNKwmUIxawrJieNWIFD+0pHdmZ8UFG/nWnompSaiSc9v5JtvyxEU3PFZJMaHNrRhDlJoBkeh4AerVRT700gNWCLEEPwniqpgLbXq3ZPY5qK63xczCJ+xAha8z5Nyf1v97E2dNnS08ADogI6SxORgp+skJP58pgypvdd0Y4d6SvGwfbo/lzfdY5RRw57E0/bPu1643SNKTkZQvWyoOnyZ/xHTFWpjHzLPjx6TkRTqbEezBq6A6DtMzSEWsIgr4iPqPcX9MBzmH6xDoVRBvitZMDEygiyGDSgvQhJrj9eUpcAcRTsH80Gp5rW3B1G0lY5iPOKNxe1IzZPrOic4u9uWzX4srWmxxQz2SYQd2fnXuWTBqzk+2wjBMaQa/k2/AhZ8jGsW2/BzbDxzkWoXYL93mUcE76oqfQfntgpfUFT```

**Comment by Gujal00** [comment]
That site is not a video hoster. ResolveURL only supports genuine filelockers. Not sure if that site should be supported by ResolveURL
