### ISSUE TITLE
Streamtape

### ISSUE THREAD

**Issue by dober2** [Gujal00/ResolveURL#154]
Hello,

streamtape doesnt seem to work at the moment. Have they changed anything?
example links: 
```
https://streamtape.com/e/e0qoegLPDdhYl8j/CUTJMxZ6iCWIjdPQjpwDhBXm6u6LOOrgZXbHd8J0AvKVH.mkv

https://streamtape.com/e/BQ7ZAVLmjafyg4Z
```

**Comment by Gujal00** [comment]
It is seeing a cloudflare ddos protection page. Nothing can be done in the plugin for now

**Comment by dober2** [comment]
Thank you. I already wondered because at least on php i did not receive a cloudflare protection site.

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/65c017fb30e5388481cfebe97c3686dc1237b3cf
