### ISSUE TITLE
Can I resolve a url link not shown until clicked?

### ISSUE THREAD

**Issue by ppongoo** [Gujal00/ResolveURL#178]
I tried to resolve a url link (evoload or mixload) wrapped by 3rd party script.
A media url won't be shown before play button is clicked.
Could you help me on this one?

https://pastebin.com/Hc0cydLh

**Comment by shellc0de27** [comment]
Well the real evoload might be dead as of now. However, that url looks to be an embedo domain in which we can add and resolve if you want? Just need to add and test

**Comment by Gujal00** [comment]
> I tried to resolve a url link (evoload or mixload) wrapped by 3rd party script. A media url won't be shown before play button is clicked. Could you help me on this one?
> 
> https://pastebin.com/Hc0cydLh
Snippets of the html page is of no use. Provide the main url so that it can be assesed what javascripts are getting called and if it suitable to add to ResolveURL

**Comment by ppongoo** [comment]
> 

definitely! That would be great if you add it. But as of now how to get the main url? Can it be done by tracing back to the code in the thumbnail URL? I guess not 😭

**Comment by ppongoo** [comment]
> Well the real evoload might be dead as of now. However, that url looks to be an embedo domain in which we can add and resolve if you want? Just need to add and test

definitely! That would be great if you add it. But as of now how to get the main url? Can it be done by tracing back to the code in the thumbnail URL? I guess not 😭

**Comment by shellc0de27** [comment]
@ppongoo So the url you need to resolve is `hxxps://embedo.co/f/d3lqfizxc3pm/` ?

If so ResolveURL already handles it as you can see below.
`SMR Link Tester: Link Supported: |https://embedo.co/f/d3lqfizxc3pm/| Resolvers: UpVideo`
`SMR Link Tester: Link Resolved: |https://embedo.co/f/d3lqfizxc3pm/|https://4dc081874712173.embedocdn.com/atlaslionzd/1ZzfbvL3gLqWgq7ZfN5eUw/1660866737/r6krgbbpxabj/dgzlhp8ofnb2/video.mp4|Referer=https%3A%2F%2Fembedo.co%2Fe%2Fd3lqfizxc3pm&Host=evoload.xyz&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A68.0%29+Gecko%2F20100101+Firefox%2F68.0&verifypeer=false|`

**Comment by ppongoo** [comment]
😱 oh my... I feel stupid. I should have searched the url in library. 
but then again do you have any trick to trace back a hoster url from something '****cdn' url? sometimes google don't tell me so..
Again, thanks for your help :)

**Comment by shellc0de27** [comment]
No worries man 👍
