### ISSUE TITLE
Custom Progress dialog doesn't display line 3 on Kodi 19

### ISSUE THREAD

**Issue by host505** [Gujal00/ResolveURL#18]
...at least on ResolveURL Real-Debrid Transfer dialog (it does appear on kodi 18).
Some findings from my digging about it:

- `CountdownDialog` that uses the same `CustomProgressDialog.ProgressDialog()` class and xml does show line 3 (on eg r-d auth dialog). _EDIT: that's wrong sorry, CountdownDialog has the same problem too_
- Using standard `xbmcgui.DialogProgress()` does show line 3 on that specific dialog, so I guess lines joining to 1 has been done correctly.

So, not sure if there's something wrong on the xml, the `CustomProgressDialog.ProgressDialog()` class or the call for `kodi.CountdownDialog()` on realdebrid.get_media_url that makes line 3 to not appear on kodi 19.

**Comment by Lav1019** [comment]
Please look into dood.watch streams, unable to play them.

**Comment by Gujal00** [comment]
@Lav1019 please open a new issue when reporting, do not report on an completely unrelated existing issue.
Also my test embeds for dood are working fine. If the embed is working in a browser, provided it to me so that I can check

**Comment by Gujal00** [comment]
@host505 Can you tell me on what platform you are facing this issue?
On Windows Kodi Leia and Matrix both show the 3rd line correctly
![image](https://i.imgur.com/T1qYf4y.png)

On my Android emulator running on WIndows, the 3rd line shows too
![image](https://i.imgur.com/brxB33p.png)

**Comment by host505** [comment]
That is not smr's custom progress dialog, it's kodi's built-in one. The problem exists on smr's custom pd.
The appearance of custom pd is conditional:
https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/lib/resolveurl/lib/kodi.py#L281-L284,
https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/lib/resolveurl/lib/kodi.py#L343-L346
Link-tester only sends one link to smr, but a scraper add-on will typically create a list of x urls and send them to smr one by one, and this will be visually displayed through a progress dialog, so the `if` condition of the code linked above will be met and smr will use the custom pd.

![screenshot00000](https://user-images.githubusercontent.com/10226596/160271888-11974a3c-2b9e-4311-85cf-dac2c566acf5.png)

Now, not sure why we even use a custom pd, but I remember in the past previous maintainers trying to remove it but it produced some problems with it closing when needed - and I also confirmed that by bypassing it and trying to use kodi's pd.
Don't know what the deeper issue is.

**Comment by Gujal00** [comment]
The custom dialog is used here to show the countdown, the progress bar shrinks as opposed to Kodi default of growing. The screenshots above, the progress dialog comes from resolveurl, not link tester
You didnt mention which platform you are testing. Is it windows?

**Comment by host505** [comment]
I know the progress dialog you posted is from resolveurl, I'm just saying that in the case of it being initiated from link tester it'll initiate the standard kodi progress dialog, but if it's triggered through a scraper add-on it will initiate smr's custom pd, for the reasons I explained.
The ss I posted is from windows, but it's the same on android and coreelec - all with kodi 19.

**Comment by Gujal00** [comment]
okay there may be a issue when custom progress dialog overlays on top of an already showing progress dialog in Kodi19. Will dig further. Thanks

**Comment by jewbmx** [comment]
While this issues open and being seen, id like to notify you of a possible error in the settings for the universal resolvers category lol. When trying to make it to the bottom of the section it glitches out at when i think is the last one. Havent really looked at it further. Using kodi 19 if useful.

**Comment by Gujal00** [comment]
Yep, thats been like that for a while, i didnt bother as the last two Smoozed and Zevera were broken anyway :)
Will fix it in a future release by splitting it into two

**Comment by jewbmx** [comment]
If they are broken id just remove a few lines from em to make it all fit still or remove one if not both lol. My thoughts on splitting it into 2 categories were under the assumption that they were all working properly but a couple lines to many altogether lol.

**Comment by host505** [comment]
Well the same applies for the Resolvers categories too.
I think `MAX_SETTINGS` needs to change to 60 or something.

**Comment by jewbmx** [comment]
Ive thought that number should be 60 or 70 too since the last time i recall it needing updated lol think it was also during a sorta deep clean of the resolvers.

**Comment by Gujal00** [comment]
@host505 Can you test this commit https://github.com/Gujal00/ResolveURL/commit/9d7929c78b014a15041e57c9df07b5de4e69fdf5
This commit should fix line 3 in custom dialog. Please test and let me know

@jewbmx this commit also contains the fix for unreachable option in universal resolvers.
Once you apply the commit, you need to run smrlinktester once so that a new settings.xml gets created and then you should see that the universal resolvers is split into 5 max per section and all settings are reachable

**Comment by host505** [comment]
Yes, line3 on custom pd appears ok now 👍🏻 
Tested with real-debrid transfer and uptobox pin dialogs.
Also, did you see my message above about `MAX_SETTINGS`? I think this needs adjustment too, as some resolvers settings at the bottom of each category are inaccessible with arrow keys.

**Comment by host505** [comment]
Damn, as I suspected, the changes on xml you did broke custom pd under kodi 18.
I think we need a change in approach here and combine all lines for the dialog's msg into 1, regardless of kodi version.

**Comment by Gujal00** [comment]
@host505 Okay made a slight change, please pull and test

This is in Kodi 18, there is a gap between line1 and line2, shouldn't be a major noticeable issue
![image](https://i.imgur.com/K6QZhbi.png)

And this is in Kodi 19, no gap between line1 and line 2
![image](https://i.imgur.com/eiM9mLD.png)

**Comment by host505** [comment]
Okay that'd work, however my proposal would be this:
https://github.com/host505/ResolveURL/commit/9758f0a3dba7c1ffa8af02770b3e97a98ba527f2

**Comment by jewbmx** [comment]
If Lav1019 is still having trouble with the dood resolver, some domains are likely down so if your do a domain swap to one you know works they will play for ya. Or the resolver could be "hard coded" with a working domain instead of using whichever it starts with lol. I stuffed them and others into a custom def in one of my modules to do the swap before i play anything lol

**Comment by host505** [comment]
Sorry I didn't test after your latest commits under k19 (was too busy testing krypton & leia lol) but [this](https://github.com/Gujal00/ResolveURL/commit/08112eaa7edaca7a6a19686bc37cadbf83e3c2da) broke line3 on k19+.
[line1 height](https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/resources/skins/Default/720p/ProgressDialog.xml#L68) must be bumped to 46 for line3 to appear, and if there's a fourth line it needs to be bumped to 68.
Of course the later case (height 68) completely messes up dialog on kodi <= 18.

**Comment by Gujal00** [comment]
I dont see any issue with line 3 in K19
![image](https://i.imgur.com/cswiRB6.png)

**Comment by host505** [comment]
I believe the problem is ui resolution conditional.
Kodi ui set to 1920x1080 or lower will have the problem. What is your ui set to?

**Comment by Gujal00** [comment]
1280x720 on my VMs
1920x1080 on my CoreElec box
![image](https://i.imgur.com/MPdN10O.png)

**Comment by host505** [comment]
Yeah I'm using the default skin with default font.
I can reproduce the problem with Greek & English ui.

**Comment by host505** [comment]
You nailed it, it's the font. Changing to Arial based makes line3 appear.
I still believe it should work with the default font though.

**Comment by Gujal00** [comment]
As I said, I do not use the default font, I use Arial Based Font because it supports asian languages.
This is windowed mode 1024x576
![image](https://i.imgur.com/k9z25cI.png)
![image](https://i.imgur.com/VNClmFy.png)

**Comment by host505** [comment]
Yes, it's not ui res based after all, it's just font.
On my phone that I said it worked, I had changed the font to Arial based already.
Changing it to Arial based on the other platforms makes line3 appear as well.
I don't know your view about this but I personally want foremost for things to work on vanilla situation.
Yes, default font sucks, but it's default...
I already reported above what line height works for it.

**Comment by Gujal00** [comment]
@host505 
You are absolutely right that it should work with default font.
Please pull the latest commit and test in K16-K19

I dont know why I didnt do this before. Just left the old xml alone for K16 to K18 and made a new XML for K19+ :joy:

**Comment by host505** [comment]
Tested k17-k19, all working ok, custom pd and xbmcgui pd - even with the odd 4th line on Greek translation.
(as I said elsewhere, can't install recent versions of smr on k16 due to it's certify module dependency)

**Comment by Gujal00** [comment]
Ah, smr used to work only in k16 under linux anyway due to the bundled python on other platforms not supporting tls1.2, ao not a big loss. K17 onwards it is then.

So if you have tested and happy please close the issue. I will leave it open for you to test it thoroughly

**Comment by host505** [comment]
Add spmc to the losses (an android k16 fork with ssl support) which some people apparently still use - I recently got an issue on my gh that one of my updates broke usage on spmc lol. It was not a big deal so I fixed it.

I think I tested whatever I could - k17-k20(!) on win and k19 on android & corelec - but I'll leave it open for a day or so if something else comes up and then close.

**Comment by Gujal00** [comment]
@host505 if there are people still using Jarvis or SPMC, I think I can work around certifi requirement. Do you want to test that?

**Comment by host505** [comment]
Don't know, they're probably stuck on an old smr version (5.1.43 I think is the last one supported in k16).
I can barely see a usage for spmc, in the case of some really old devices stuck on android < 5 (k17+ requires android 5+), so if you want to support that sure I can test.
I can not excuse the usage of k16 on any other case/platform - as you said it's useless without ssl support, and in the case of linux there's nothing stopping someone using newer versions.

**Comment by Gujal00** [comment]
People with Android 4.4 boxes were stuck on SPMC, but then Kodi 17.1 was ported to Android Kitkat by MyGica, dont know why they would still use SPMC.
Anyway, please try this https://github.com/Gujal00/ResolveURL/tree/feature-no-certifi and if successful i will merge into master branch

**Comment by host505** [comment]
Okay, this is gonna take a while though as it needs testing under all supported kodi versions, and it's a busy week ahead.
Thanks

**Comment by Gujal00** [comment]
No worries mate. Take your own time. Cheers

**Comment by host505** [comment]
@Gujal00 I tested this branch on every platform/version I could: windows kodi 17-20, android/coreelec 19 and spmc 16 - all seemed to be working ok.
What I tested was magnets and hosts resolved by real-debrid, and some regular hosts with their own resolvers.
Anything specific I should be testing?

**Comment by Gujal00** [comment]
Excellent. I will merge it into the master branch. Please pull the master branch and test hoster doodstream/dood (uses cflare browser fingerprinting blocks) in SPMC and K17. I have tested it in K18 and seems to work fine. Thanks

**Comment by host505** [comment]
Re-authorising rd doesn't work in k19 with current master... It did work with the alternate branch implementation you posted.

```
2022-04-09 13:19:18.878 T:1776    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'client_id'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\host505\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 185, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\host505\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 181, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\host505\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\url_dispatcher.py", line 85, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\host505\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 66, in auth_rd
                                                       if realdebrid.RealDebridResolver().authorize_resolver():
                                                     File "C:\Users\host505\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\realdebrid.py", line 304, in authorize_resolver
                                                       return self.__get_token(result['client_id'], result['client_secret'], js_result['device_code'])
                                                   KeyError: 'client_id'
                                                   -->End of Python script error report<--
```

**Comment by Gujal00** [comment]
@host505 yes the error has creeped in due to the changes i did for handling cflare 403 error. Have fixed now. Please pull and test. I have tested in WIndow K18 and K19 and works correctly

**Comment by host505** [comment]
K17 & spmc ok too 👍🏻

**Comment by Gujal00** [comment]
Perfect. Thanks for that. Will package and release
