### ISSUE TITLE
vidjet support

### ISSUE THREAD

**Issue by kolekan** [Gujal00/ResolveURL#195]
Please can you add support for links like `https://vidjet.me/v/89ME5QEuFeW5Vad`
Thanks you!

**Comment by Gujal00** [comment]
Dead embed, cant do a plugin, i found two more embeds but they return 0 bytes as the content-length on the browser. Cant do a plugin unless a working embed is found

**Comment by kolekan** [comment]
I see..... i'm closing this until i find a working one. Thanks!
