### ISSUE TITLE
Deccan delight not working

### ISSUE THREAD

**Issue by kuku45** [Gujal00/ResolveURL#201]
I updated the Repository to 2.0.1 and now I get an error message. Deccan delight has stopped working. is there a way to revert back to repository 2.0.0

**Comment by Gujal00** [comment]
Please do not raise issues unrelated to ResolveURL in this repository

**Comment by kuku45** [comment]
Thank you for your response. Sorry for the wrong post.
I updated the repository to the latest version and now I am having error.
Please let me know how to proceed.
