### ISSUE TITLE
edit doodstream.py

### ISSUE THREAD

**Issue by kasi45** [Gujal00/ResolveURL#208]
https://kinomax.click/61-men-in-black-international-stream-deutsch.html
in the source text of the website
```
<a data-link="https://dood.to/e/zhueszjwaqmq" href="#"><span class="masha_index masha_index23" rel="23"></span>Doodstream</a>
```

https://kkiste.show/7144-men-in-black-3-stream-kinox.html
in the source text of the website
```
<span data-link="https://dood.to/e/h8l1h9keiz4d" class="active"><img src="/templates/kkiste-dark/images/doodstream.png" height="17" alt=""> Doodstream</span>
```

the domain "dood.to" no longer exists, but the stream does! 
You only need to change "dood.to" to "doodstream.com" or to another available "dood" domain

edit doodstream.py
```
if host.endswith('.cx') or host.endswith('.to'): 
    host = 'dood.so'
```

thank you very much

**Comment by shellc0de27** [comment]
The `dood.to` domain exists and resolves both of those for me as you can see below. Might run a little slow atm but works.

![dood1](https://user-images.githubusercontent.com/50564043/190921164-cd7eb3a8-66c4-470b-ae86-577924472a6b.PNG)

`SMR Link Tester: Link Resolved: |https://dood.to/e/h8l1h9keiz4d|https://fio166p.dood.video/u5kj2jls5xglsdgge72empsoiqv7pleczkdxfywzaqqr6nhrcmzjboi4g63a/z7b9whpa8d~d7GkyZ597S?token=zfezo2ctj57q0xsc0v8inn9l&expiry=1663522692352|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F70.0.3538.102+Safari%2F537.36+Edge%2F18.18363&Referer=https%3A%2F%2Fdood.to%2Fd%2Fh8l1h9keiz4d|`

![dood2](https://user-images.githubusercontent.com/50564043/190921268-c5a039a9-da59-4804-9c65-59e059254f6d.PNG)

`SMR Link Tester: Link Resolved: |https://dood.to/e/zhueszjwaqmq|https://p302kl.dood.video/u5kj6gvza3glsdgge76hsla6lunoysstrsco7qkyk7p7hyxxl6yr2o33acra/h2vpt7ykcx~gaq0b51zYq?token=fujfyuhq7ej44s3824w3r45u&expiry=1663523338457|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_4%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F13.1+Safari%2F605.1.15&Referer=https%3A%2F%2Fdood.to%2Fd%2Fzhueszjwaqmq|`

**Comment by kasi45** [comment]
Thank you for checking
I have found the cause!
"dood.to" was blocked by "pi.hole" DNS
