### ISSUE TITLE
Real-debrid must be reauthorized every day

### ISSUE THREAD

**Issue by EvilCaptKirk** [Gujal00/ResolveURL#211]
See the same issue also posted here, started by someone else: https://github.com/team-crew/team-crew.github.io/issues/93

Real-debrid currently needs to be reauthorized every 24 hours, whereas before, this was not the case. The issue began sometime this Summer, probably when the other fellow opened his issue on The Crew GitHub. Users of other streaming addons reported they are/aren't having the problem, and some have suggested that it could be a problem with ResolveURL rather than the streaming add-on, so I'm posting it here just in case.

I've experienced this issue on both Linux and Windows installs of the 19.x branch of Kodi, The Crew v1.1.6b, ResolveURL 5.1.64. I've tried the fix suggested here - editing realdebrid.py and re-authorizing:
https://www.reddit.com/r/Addons4Kodi/comments/v7zzer/reauthorize_realdebrid_every_day/ 
...but the issue persists. 

Appreciate any suggestions on further troubleshooting steps.

**Comment by bleak-lodge** [comment]
> ResolveURL 5.1.64

We're currently on version 5.1.76, so you're stuck with an old and (apparently) problematic version, probably because you had smr installed through a now dead repo.
Kodi 19 won't automatically update it from another repo, so you have to do it manually.
I suggest you install the resolveurl's own repo and update it from that.

**Comment by EvilCaptKirk** [comment]
Thanks, I realized that right after I posted this. I've got the updated version installed from an active repo and we'll see how it goes. I'll post an update, thanks for replying.

**Comment by Gujal00** [comment]
@EvilCaptKirk is that working correctly for you with the newer SMR versions?

**Comment by EvilCaptKirk** [comment]
Yes, after a week or so, I can confirm that the upgrade definitely fixed the issue. I'll have to keep an eye on the dead repos situation going forward. Thanks for your help!
