### ISSUE TITLE
streamsb not work again

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#215]
hi guys, streamsb not work again, HTTP 404 error but file is online and work correctly on browser.

I attach a part of log
[streamsb.txt](https://github.com/Gujal00/ResolveURL/files/9631111/streamsb.txt)

**Comment by Gujal00** [comment]
may be you are not using the current git version. but this was fixed in https://github.com/Gujal00/ResolveURL/commit/1cde1f4cc4a54f8efc78bbf08f0ad0ab0db6b8d1 and https://github.com/Gujal00/ResolveURL/commit/e980bba0bb40cadbba54a379153134a40fe5ae63.

**Comment by soter80** [comment]
> may be you are not using the current git version. but this was fixed in [1cde1f4](https://github.com/Gujal00/ResolveURL/commit/1cde1f4cc4a54f8efc78bbf08f0ad0ab0db6b8d1) and [e980bba](https://github.com/Gujal00/ResolveURL/commit/e980bba0bb40cadbba54a379153134a40fe5ae63).
> 
> ```
> SMR Link Tester: Link Resolved: |https://sblanh.com/bgx5lihs028x.html|https://delivery337.akamai-cdn-content.com/hls2/01/07531/bgx5lihs028x_,l,n,.urlset/master.m3u8?t=8QlRAlwRu6RleoMIJecW9-mrTDMxHXG72bJMpJ05X5c&s=1663914630&e=10800&f=37655618&srv=sto074&client=222.155.41.20|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F70.0.3538.102+Safari%2F537.36+Edge%2F18.18363&Referer=https%3A%2F%2Fsblanh.com%2F|
> ```

sorry bro, :-(
