### ISSUE TITLE
I need fix redtube

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#23]
redtube updated, need to update the plugin in the adult resolver

**Comment by Gujal00** [comment]
What is the issue? seems to work fine
`
SMR Link Tester: Link Resolved: |https://www.redtube.com/40878431|https://ee-ph.rdtcdn.com/videos/202112/29/400408881/480P_2000K_400408881.mp4?validfrom=1645037845&validto=1645045045&rate=139k&burst=1400k&hash=w4X8hoC7F4mz%2FZxBVmW4Hkc1X64%3D|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F80.0.3987.132+Safari%2F537.36+OPR%2F67.0.3575.97&Referer=http%3A%2F%2Fembed.redtube.com%2F&Cookie=ua%3D897dd7bf6b33952e4282a96743117863%3B+expires%3DThu%2C+05-Apr-2074+15%3A54%3A50+GMT%3B+Max-Age%3D1645127845%3B+path%3D%2F%3B+domain%3Dredtube.com%2Cplatform%3Dpc%3B+expires%3DThu%2C+05-Apr-2074+15%3A54%3A50+GMT%3B+Max-Age%3D1645127845%3B+path%3D%2F%3B+domain%3Dredtube.com%2Cbs%3Daw9rz20miagm2sbwjgs4bohnivd6wd78%3B+expires%3DSat%2C+01-Apr-2084+15%3A54%3A50+GMT%3B+Max-Age%3D1960401445%3B+path%3D%2F%3B+domain%3Dredtube.com%3B+secure%3B+SameSite%3DNone%2CRNLBSERVERID%3Dded6784%3B+path%3D%2F%3B+Secure%3B+SameSite%3DNone&Origin=http%3A%2F%2Fembed.redtube.com|
`
