### ISSUE TITLE
Using the mobile browser as a resolver

### ISSUE THREAD

**Issue by doko-desuka** [Gujal00/ResolveURL#279]
Hi Gujal00. It's because of little changes like these:
- https://github.com/Gujal00/ResolveURL/pull/276
- https://github.com/Gujal00/ResolveURL/pull/265

...that I was thinking if there wasn't a definitive solution.

Using the WebExtension API we can create a browser extension that can listen to the headers and destination URLs of all requests that your browser makes.  
So I tested making an extension that did that: https://github.com/doko-desuka/StreamCatcher  

On Kodi, in an add-on, you have some Python code listening until it receives the URL + headers that the extension on the phone has prepared and sent it:  

https://user-images.githubusercontent.com/31810999/208303230-335949e9-6da6-4653-9b59-b02ff67cce5a.mp4

It's working on an Android phone (using the Kiwi browser) + Android TV box setup.  
There's a few sources it can't detect, but there's also some reCaptcha-protected videos that it's able to reach, because the browser passes the test of course. Anything you can watch on the Kiwi browser is potentially playable on Kodi.  
I think this can finally make so many updates unnecessary. The process becomes:  
1. On Kodi you activate your plugin for it to start "listening" on some address & port.
2. On your phone you go to a website as if you're going to watch something.
3. Wait for the extension to detect a video being played (it's automatic).
4. Send details to Kodi through that address & port.
5. Kodi plays it, instead of your mobile browser.

And this isn't cheating, as we aren't scraping anything: we're visiting these sites on our phones, so we're shown ads, promotions etc. The website owners aren't being explored. This is simply "instead of playing it on my phone screen, play it on my Kodi device".  

Cheers

**Comment by Gujal00** [comment]
Welcome @doko-desuka Yes it is a neat idea, but should be used as a last resort probably for sites locked behind click captcha/recaptcha such as netu or heavy js obfuscation such as mycloud/streamrapid.
Sites that can be silently resolved such as the sites already in SMR should be left alone as they work already without user intervention.
However I am not fond of browsing these sites on my mobile phone due to nature of ads on Android and data exfiltration, but will see if it can be added as an option and leave it to the user to decide

**Comment by doko-desuka** [comment]
Thanks for reading all of that @Gujal00. I wanted to let you know about the reference code in there, so since you saw it I'll close this now.

I've thought of a way to improve the process so I don't have to go around the web searching for sources.  
Since we can create a simple Python server in a running Kodi plugin (even on an Android TV box, which is supposedly more locked-in, less permissions), if on your phone you access the static local IP address\* of your Kodi device, the server can offer an HTML page with links to sources that it found. This way less clicking is involved:  
1. On your mobile browser, visit the address of your Kodi device.
2. Kodi has a plugin running a simple Python socket server (that will receive a GET request from the browser).
3. Server responds with an HTML page with a list of links to embedded players that the Python plugin found, and the list appears on the browser.
4. Click a link to go to the embedded player, let the extension detect the media.
5. Send it for Kodi to play.

\* For others like me who are new to IT, a static local IP address is usually something like 192.168.1.### (with ### being for a number between 1 and 255), which you set up in the Wi-Fi or Ethernet system settings of your Kodi device. You need to use a static local IP instead of dynamic IP with DHCP for the Kodi device, because the browser extension needs to know where to send the POST request with info about the video request.

**Comment by doko-desuka** [comment]
(Oh, and I had to install uBlock Origin on Kiwi browser because, as you said, there were so many ads that some hosters were literally unplayable because each click redirected the video player page... Thankfully uBlock solved that for now.)

**Comment by Gujal00** [comment]
Yeah that is the reason why I dont like to ask average users to browse to ad laden sites on a mobile browser. It is okay for tech savvy people but the average user would use it without a proper setup and then complain that kodi infected their mobile phone with malware.
