### ISSUE TITLE
Doodstream strange behaviour

### ISSUE THREAD

**Issue by eXim82** [Gujal00/ResolveURL#305]
Hello

When i play a doodstream with xstream it fails. It happens on my tv and on my smartphone. Now comes the strange part. If i start the stream trough the mobile network instead of wifi it works on tv an smartphone. Even stranger. If i open the hoster on my mobile directly in the browser with wifi. It works and then it will work on kodi on the tv and smartphone directy with wifi. But this workaround doesnt works if i use kodi for the mobile network trick. Very strange.

Here the link for example from the log. Happens to all dood streams.

When it fails, the link in the log is this one:
DoodStream Link: https://dood.to/e/pholfjelztbd: Video Link Not Found

Here when the link starts strangerly working, as explained before. Sorry its too long the second  link in the log:
https://dood.to/e/pholfjelztbd
https://d521mk.dood.video/u5kjoybmhsdgge5ncgjq6i6zdiyaigl6wblj4yzibpchb4pydpazo......

**Comment by Gujal00** [comment]
May be location dependant. test with a VPN if possible

The link works fine here
```
INFO <general>: SMR Link Tester: Version: |1.1.9| Queries: |{'mode': 'play_link', 'link': 'https://dood.to/e/pholfjelztbd'}|
INFO <general>: SMR Link Tester: Running on: Python 3.8.15 (default, Oct 17 2022, 02:39:57) [MSC v.1929 64 bit (AMD64)]|OpenSSL 1.1.1q  5 Jul 2022
INFO <general>: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '3', '?mode=play_link&link=https%3A%2F%2Fdood.to%2Fe%2Fpholfjelztbd', 'resume:false']|
INFO <general>: SMR Link Tester: Playing Link: |https://dood.to/e/pholfjelztbd|
INFO <general>: SMR Link Tester: Link Supported: |https://dood.to/e/pholfjelztbd| Resolvers: DoodStream
INFO <general>: SMR Link Tester: Link Resolved: |https://dood.to/e/pholfjelztbd|https://dc521mk.dood.video/u5kj6ybm4hflsdgge5ncgjq6i6lzdjyaigl6wxblj4yzjoxkkm6oo6rjn7lq/koy8quuc9l~P8OMAVlG34?token=52vllvgffnt7gfurm7cm4djv&expiry=1674070083226|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F70.0.3538.102+Safari%2F537.36+Edge%2F18.18363&Referer=https%3A%2F%2Fdood.to%2Fd%2Fpholfjelztbd|
```

Need a full debug log to see what is happening anyway

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3.  Restart Kodi **(Important)**
4. Go into to xstream and try playing the doodstream link (wait for the error message)
5. Come out of xstream
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

**Comment by Gujal00** [comment]
Okay you are running `script.module.resolveurl v5.1.89~nightly2` which has got nothing to do with this repository. It is xstream's own fork and you need to take it with them
