### ISSUE TITLE
Need help to resolve the streamsb host

### ISSUE THREAD

**Issue by sviet2k** [Gujal00/ResolveURL#316]
Hi,

I guess the streamsb.py does not support the following link:
`https://streamsb.net/embed-ni83hdnjejff.html`
There is no keyword 'download_video' in the response.
Can you please help me to fix this issue?
Thanks in advance for your help

**Comment by shellc0de27** [comment]
@sviet2k That link is supported and i fixed this a couple weeks ago as you can see in the following commit 8dd2b04 .
This will be in the next release 😃

**Comment by Gujal00** [comment]
v5.1.88 released
