### ISSUE TITLE
New Resolver Streamembed

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#320]
I found a new Website `https://streamembed.com/`
Find on `https://megakino.co/films/2529-i-love-my-dad-ein-papa-zum-knutschen.html`
Iframe Link `https://mp4player.site/watch?v=7YTF9XU2`

It would be great if you could create a suitable resolver for this.

Kind regards

**Comment by shellc0de27** [comment]
@Gujal00 I can add this to resolveurl when I get home if you want. Made the resolver sometime ago, will just need to add this other domain and test

**Comment by Gujal00** [comment]
Added in #321
