### ISSUE TITLE
New Resolver archive.org

### ISSUE THREAD

**Issue by Heptamer** [Gujal00/ResolveURL#322]
Would it be possible to add the video files on archive.org to resolveUrl?

Example: https://archive.org/embed/hsadr-tsuadnle-cehn

Thanks in advance for looking into it!

Best regards

**Comment by Gujal00** [comment]
Added in https://github.com/Gujal00/ResolveURL/commit/9fd0d4089009885296a780e3e1c49cbece040d48

**Comment by Heptamer** [comment]
Thanks, much appreciated!
