### ISSUE TITLE
Deccan delight-resolve URL error

### ISSUE THREAD

**Issue by rubanrex** [Gujal00/ResolveURL#325]
Hi,

The Deccan delight add-on was working for fine, suddenly getting Resolve URL error for tamilyogi links. How to fix this please?

Thanks in advance.

Bw

Ruban

**Comment by Gujal00** [comment]
This forum is for ResolveURL, please do not pollute it with addon issues. Test whatever link is failing with SMR Link tester and if it is still failing provide the embed link here
