### ISSUE TITLE
highload

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#34]
https://highload.to/e/9nzrtt8mgmlc/

**Comment by Gujal00** [comment]
What is the issue?
ResolveURL is resolving that link correctly
`
SMR Link Tester: Link Resolved: |https://highload.to/e/9nzrtt8mgmlc/|https://5586b6eaaca3b24.highdeliverycdn.com/atlaslionzd/jbY-_qLMgZoNrPMd1uf7dg/1646970921/lpptxr3khzmj/qhtrejdolohn/video.mp4|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36&Referer=https%3A%2F%2Fhighload.to%2Fe%2F9nzrtt8mgmlc|
`
