### ISSUE TITLE
voe.sx "File access denied"

### ISSUE THREAD

**Issue by dober2** [Gujal00/ResolveURL#342]
Probably depending on a setting the uploader can set, voe shows the following message now:

"File access denied
The owner of this file has restricted access."

Is there a way to work around this?

**Comment by DWH-WFC** [comment]
If you click play on a movie with VOE it will redirect and redirect to the URL.

But if you copy and paste the link, it will be blocked.
Although the url is correct and the same.

**Comment by DWH-WFC** [comment]
All VOE Links with */e/* works fine.

https://voe.sx/e/xl435pspu2vf

You can copy and paste it.

The Links without /e/ not working on browser.

**Comment by dober2** [comment]
At the moment the "File access denied" doesnt appear for me anymore.

**Comment by DWH-WFC** [comment]
seems to have been a temporary problem because the links are working now.
