### ISSUE TITLE
[streamrapid.py] New URL add ?

### ISSUE THREAD

**Issue by lavara123** [Gujal00/ResolveURL#343]
example url:

https://rapid-cloud.co/embed-6/3XY8dq59fByQ?vast=1

**Comment by Gujal00** [comment]
Seems to be another domain for streamrapid/rabbitstream. Can't do it as it is the same rolling obfuscated javascript

**Comment by lavara123** [comment]
> Seems to be another domain for streamrapid/rabbitstream. Can't do it as it is the same rolling obfuscated javascript. same issue #205

I solved that rolling event, I just opened it to add rapid-cloud.co at this address, a new address should be set to the "domains" variable

**Comment by shellc0de27** [comment]
> 
> I solved that rolling event, I just opened it to add rapid-cloud.co at this address, a new address should be set to the "domains" variable

If you solved it, why open an issue for just a domain vs creating a pull request with your code?

**Comment by lavara123** [comment]
> > I solved that rolling event, I just opened it to add rapid-cloud.co at this address, a new address should be set to the "domains" variable
> 
> If you solved it, why open an issue for just a domain vs creating a pull request with your code?

It works with the dart code I made and at the end of the process with the js engine (Quickjs)

I don't know if it is possible to run js engine with Kodi too?

**Comment by shellc0de27** [comment]
@lavara123 No point in adding a domain to a resolver written in Python for a project which runs in kodi in which you have not actually solved! :man_shrugging: and just adding the domain is completely pointless cause its still broken.

**Comment by Gujal00** [comment]
@lavara123 unfortunately kodi cant do js. There are some who use bhrome browser and selenium to solve but then it is not universally doable for all platforms that ResolveURL supports. so yeah the domain can be added but it is still a broken resolver
