### ISSUE TITLE
viewsb

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#35]
https://viewsb.com/e/04as6j2gg29i.html

**Comment by Gujal00** [comment]
What is the issue?
ResolveURL is resolving that link correctly
`
INFO <general>: SMR Link Tester: Link Resolved: |https://viewsb.com/e/04as6j2gg29i.html|https://www221.akamai-cdn-content.com/tysxedem6o6oj6cdaauathyfek2leynmigyiviljfpkkknxypoglmnu5cwgq/The.Batman.2022.720p.CAMRip.Dublado.mp4|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F84.0.4136.7+Safari%2F537.36&Referer=https%3A%2F%2Fviewsb.com%2F|
`
