### ISSUE TITLE
Resolver Goodstream.uno not working

### ISSUE THREAD

**Issue by Heptamer** [Gujal00/ResolveURL#392]
Hi, seems since a few days Goodstream is not working anymore with ResolveURL, could you please have a look into it?

Example: `https://goodstream.uno/video/embed/2qXJ`

Thanks!

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/08117542ae9ae11ac3df3f2f20035baa2d0a173a

**Comment by Heptamer** [comment]
Thanks a Lot :)
