### ISSUE TITLE
voe.sx ?

### ISSUE THREAD

**Issue by lavara123** [Gujal00/ResolveURL#395]
Doesn't work because it's `https://ddos-guard.net/` ??

example url:
`https://voe.sx/e/j6th3fui2d3k`

**Comment by Gujal00** [comment]
ddosguard is like cloudflare, canvas replies in javascript. It can't be bypassed. Usually it is activated in a region by region basis, so you could try with VPN if they have activated in your region

**Comment by lavara123** [comment]
> ddosguard is like cloudflare, canvas replies in javascript. It can't be bypassed. Usually it is activated in a region by region basis, so you could try with VPN if they have activated in your region

Is it possible to get help from here?
https://github.com/4miners/axios-ddos-guard-bypass

**Comment by Gujal00** [comment]
No cant be done as you cant run node.js inside kodi

**Comment by lavara123** [comment]
> No cant be done as you cant run node.js inside kodi

No, I was talking about converting the codes to python

**Comment by Gujal00** [comment]
> > No cant be done as you cant run node.js inside kodi
> 
> No, I was talking about converting the codes to python

Not possible, as the node.js is used to execute the code pushed by ddg/cf so that the canvas reply can be made. Python cant do that
