### ISSUE TITLE
New Resolver

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#398]
Hello from Germany.

Is it possible to create a resolver for this provider `https://www.secvideo1.online/`?

Video: 
```
https://secvideo1.online/embed/674600/
https://secvideo1.online/embed/675728/
```

Thank you in advance for your trouble

**Comment by Gujal00** [comment]
Is the site region restricted?
```
curl -i -A iPad https://secvideo1.online/embed/674600/
curl: (28) Failed to connect to secvideo1.online port 443 after 21051 ms: Timed out
```

**Comment by DWH-WFC** [comment]
I don't know. Is a Russian site with me and is used by Kinoger.com.

**Comment by DWH-WFC** [comment]
[www.secvideo1.online.txt](https://github.com/Gujal00/ResolveURL/files/11104575/www.secvideo1.online.txt)

**Comment by Gujal00** [comment]
Added in https://github.com/Gujal00/ResolveURL/commit/0a84aa75cd6179ccb4d9ce7bc4edd61beafa8355
