### ISSUE TITLE
new

### ISSUE THREAD

**Issue by Peter3344** [Gujal00/ResolveURL#400]
hello 
is it possible to add this
https://nowvid.cfd/2down/06080233

 multi resolution

**Comment by Peter3344** [comment]
[nowvid.cfd.txt](https://github.com/Gujal00/ResolveURL/files/11114719/nowvid.cfd.txt)

**Comment by Gujal00** [comment]
Can you try with this plugin and see if it works and report back?
[nowvid.py.txt](https://github.com/Gujal00/ResolveURL/files/11128256/nowvid.py.txt)
remove the `.txt` at the end of the file name when copying to plugins folder

**Comment by Peter3344** [comment]
Not working

**Comment by Gujal00** [comment]
Then can't be done with the above information as the content seem to be georestricted to Egypt and I dont have VPN endpoint there to check how it works.

**Comment by bassemhelal18** [comment]
Ok thank you so much
