### ISSUE TITLE
Clicknupload issue 

### ISSUE THREAD

**Issue by pavlosfrank** [Gujal00/ResolveURL#404]
Hello sir.
There is an issue with clicknupload links are not playable. 
Thank you!

**Comment by Gujal00** [comment]
Please provide a working embed so that it can be  tested on the clicknupload site and resolveurl

**Comment by pavlosfrank** [comment]
https://clicknupload.red/2c9wnv2wfpzd

Στις Κυρ, 2 Απρ 2023, 12:43 π.μ. ο χρήστης gujal ***@***.***>
έγραψε:

**Comment by pavlosfrank** [comment]
This link https://clicknupload.club/2c9wnv2wfpzd
changes to  https://clicknupload.red/2c9wnv2wfpzd
If that helps, thank you so much for your work and thanks for the reply.

Στις Κυρ, 2 Απρ 2023, 12:43 π.μ. ο χρήστης gujal ***@***.***>
έγραψε:

**Comment by pavlosfrank** [comment]
Thank you very much!

Στις Δευ, 3 Απρ 2023, 12:44 π.μ. ο χρήστης gujal ***@***.***>
έγραψε:
