### ISSUE TITLE
Allviid new resolver

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#418]
`https://allviid.xyz/embed-ufbn695v48yr.html`

**Comment by Gujal00** [comment]
probably georestricted to egypt

**Comment by bassemhelal18** [comment]
[text.txt](https://github.com/Gujal00/ResolveURL/files/11227927/text.txt)

**Comment by Gujal00** [comment]
Try with this one and see if it works, you need to remove the .txt in the filename
[allviid.py.txt](https://github.com/Gujal00/ResolveURL/files/11228852/allviid.py.txt)

**Comment by bassemhelal18** [comment]
It's working thank you so much
