### ISSUE TITLE
Streamlare not working

### ISSUE THREAD

**Issue by dober2** [Gujal00/ResolveURL#42]
Looks like its broken again.

**Comment by Gujal00** [comment]
Yes they have switched to p2p again

**Comment by soter80** [comment]
> Yes they have [switched to p2p](https://www.wjunction.com/threads/streamlare-com-simple-powerful-video-file-hosting-premium-affiliate-program-event.254434/post-2476543) again

So is not possible to resolve it?

**Comment by Gujal00** [comment]
Yes it is not possible to resolve to a url playable with kodi videoplayer

**Comment by shellc0de27** [comment]
@Gujal00 Heads up, they now switched to hls and can be fixed. Had a quick look, will need to update `api_url`,  `source`, and remove `xor_string`. Thought i saw another api for downloads that do have the mp4's. Haven't done enough testing as to which would be better yet and or how you want to proceed.

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/c0df6d795009b240743e549616597ff20e5910f6
Test and report if any issues

**Comment by shellc0de27** [comment]
Seems good. For some reason the mp4's are super slow compared to their hls streams. Don't know if that's server side or something on my end at the moment. But if they stream good for you, maybe its just me

**Comment by Gujal00** [comment]
Nah, the MP4's take a while to start, most probably server load as even after startung the rate at which the file is downloaded is barely enough to keep it playing without stopping for buffering. May be switching to HLS for this provider is a better option

**Comment by shellc0de27** [comment]
Yeah I agree might be best to just handle hls for now

**Comment by Gujal00** [comment]
okay change pushed, please test again, in my test it is better than mp4 when skipping ahead a few minutes

**Comment by shellc0de27** [comment]
Cool deal, works great

**Comment by soter80** [comment]
I'm tested your fix, with link tester and it working good, thanks for your work Guys :-D

**Comment by dober2** [comment]
Thank you very much.
