### ISSUE TITLE
vidlook resolver

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#431]
`https://vidlook.net/embed-23cdz0by0g1x.html`

[vidlook.txt](https://github.com/Gujal00/ResolveURL/files/11376306/vidlook.txt)

**Comment by Gujal00** [comment]
Try with this and get back if it works, and I will include into SMR
[vidlook.py.txt](https://github.com/Gujal00/ResolveURL/files/11390916/vidlook.py.txt)
remove the `.txt` from the file name

**Comment by bassemhelal18** [comment]
It's working thank you so much
