### ISSUE TITLE
Serienstream.to (s.to) is not working since 3 weeks with XStream Plugin (release: Github preference)

### ISSUE THREAD

**Issue by vigilant4u** [Gujal00/ResolveURL#441]
Serienstream.to (s.to) is not working since 3 weeks with XStream Plugin (release: Github preference),
will there be a fix and if so until when.
It is very annoying to always have issues with the most influencial tv show streaming plattform in Germany alwys having issues that are not being fixed for weeks.

**Comment by Heptamer** [comment]
As one of the xstream developers I can tell you that all is working fine and there is no issue. Nevertheless this is the wrong place for complaining and this can be closed.
