### ISSUE TITLE
bit porno audio not work

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#443]
hi guys bitporno link have any probelms video work fine but audio non work.
```
https://bitporno.to/v/HDOQUG7CUM
https://bitporno.to/v/HDLBW6WJYF
```

**Comment by Gujal00** [comment]
There seems to be no Audio even on the browser, can you check in browser?

**Comment by soter80** [comment]
> https://bitporno.to/v/HDOQUG7CUM

Yes i've checked on browser, and the first link audio work fine. (https://bitporno.to/v/HDOQUG7CUM)
On the second link you're right (https://bitporno.to/v/HDLBW6WJYF)

**Comment by Gujal00** [comment]
Okay the first one is using a format not supported by Kodi
That is HLS stream with independent audio and video streams
`https://bitporno.to/m3u8/1802df79ac94189d495f13f3dce92c65/HDOQUG7CUM/playlist.m3u8`
```
#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="[und] ", LANGUAGE="und", URI="https://oifsv73.bitporno.to/av//a45/hdngtabvegne2lxgxhdugeskjviqlgturg.mp4.aac.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=2800000,RESOLUTION=1920x1080,AUDIO="aac",CODECS="avc1.42e00a,mp4a.40.2"
https://oifsv73.bitporno.to/av//a45/hdngsxu2862a0xkeu8i6da1ip6pajsklif.mp4.m3u8
```
Even HLS Analyser says it is invalid format
`https://hlsanalyzer.com/` try pasting that m3u8 above on the analyzer site

**Comment by shellc0de27** [comment]
@Gujal00 Cant we just return the playlist url on these, which is "surl" and forget about pulling quality? Should work fine. Cause this is happening on a few m3u8's.

**Comment by Gujal00** [comment]
Yes we can do that for m3u8s now. It was done inside SMR as the ffmpeg on older Kodi versions was not reliable in pulling the qualities, but should be fine now from Kodi 19 upwards

**Comment by Gujal00** [comment]
@soter80 I have pushed a fix which removes the pulling of qualities, you can now get audio on Kodi 19 and above. Havent tested on older versions

**Comment by soter80** [comment]
> @soter80 I have pushed a fix which removes the pulling of qualities, you can now get audio on Kodi 19 and above. Havent tested on older versions

Ok thanks, i test the fix
