### ISSUE TITLE
Tamildhool

### ISSUE THREAD

**Issue by raj10-1** [Gujal00/ResolveURL#444]
Please fix tamildhool. None of the programs are working. Thanks

**Comment by Gujal00** [comment]
Nothing to do with ResolveURL. This is not the place to report addon issues.
If there is any ResolveURL plugin not working then you can report here with the hoster embed to look at.

**Comment by raj10-1** [comment]
Sorry to ask , but where do you post addon issues?

**Comment by Gujal00** [comment]
you can [report here](https://keybase.io/gujal)

**Comment by raj10-1** [comment]
Okay thanks
