### ISSUE TITLE
streamingcommunity not work

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#457]
Hi guys, after i add the new domian of stremingcommunity I've installed the update on my kodi but file not work.

i attach the log.

[streamingcommunity.txt](https://github.com/Gujal00/ResolveURL/files/11545432/streamingcommunity.txt)

**Comment by Gujal00** [comment]
Looks like they have enabled Cloudflare captcha, cant do anything until they turn it off
![sc](https://github.com/Gujal00/ResolveURL/assets/17394059/1b74d9a7-b7c4-4415-8d68-88eb68ae5614)

**Comment by soter80** [comment]
> Looks like they have enabled Cloudflare captcha, cant do anything until they turn it off ![sc](https://user-images.githubusercontent.com/17394059/240419466-1b74d9a7-b7c4-4415-8d68-88eb68ae5614.png)

Strange when I try to connect, the recaptcha does not appear for me

**Comment by Gujal00** [comment]
Did you try with https://github.com/Gujal00/ResolveURL/commit/f3fae5d16555fbb59933dfc469b4959b5ed098a2
It should work if you are not seeing captcha

**Comment by Gujal00** [comment]
try with this commit https://github.com/Gujal00/ResolveURL/commit/a6ad36e9eb65430cc223068ec67665fb5e86113a
should work for both
