### ISSUE TITLE
Tubeload not resolving

### ISSUE THREAD

**Issue by kolekan** [Gujal00/ResolveURL#48]
Getting "Resolve failed: File not found" when trying to play [this](https://tubeload.co/e/gypd4b9mhcyp/) in SMR Link tester.

**Comment by shellc0de27** [comment]
Seems to be working fine on my end:

`SMR Link Tester: Link Resolved: |https://tubeload.co/e/gypd4b9mhcyp/|https://8a58a438d0599f9.tloadcdn.com/streaming/ehiLanLXv-uBA14BvnhIEQ/1647533392/6i40cz2ovohe/gs2zlqoord08/video.mp4|Referer=https%3A%2F%2Ftubeload.co%2F&User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A88.0%29+Gecko%2F20100101+Firefox%2F88.0&Origin=https%3A%2F%2Ftubeload.co&verifypeer=false|`

**Comment by kolekan** [comment]
here is the html output that jsunhunt produce ...
```
var dcafbcbddbcb;function init(){loveyou(function(t){dcafbcbddbcb=t?1:0})}function loveyou(t){var n=new Request("https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",{method:"HEAD",mode:"no-cors"});fetch(n).then(function(t){return t}).then(function(n){t(!1)}).catch(function(n){t(!0)})}document.addEventListener("DOMContentLoaded",init,!1);
var abfaabeaaeab="0";
var acdbebdfdfbf="Y2QzODZiNmVlYjBkYTQ0YmM2ZGZkZjI0Njc0ZTVkN2IaHR0cHM6Ly84YTU4YTQzOGQwNTk5ZjkudGxvYWRjZG4uY29tL3N0cmVhbWluZ3MvYjNBTjFlaEpmZWF4OUJRWW9BTXlZQS8xNjQ3NTQ1MzQ4LzZpNDBjejJvdm9oZS9nczJ6bHFvb3JkMDgvdmlkZW8ubXA0ZGY3Y2Q2NWUzZDE0Yzc5Njk2Y2FjNGRlZDcyYThhYTU=";
var acaefafbafac="df7cd65e3d14c79696cac4ded72a8aa5";
var bdfbcfccbdfb="QmNjZGZhZmJiZQL2dldGRsP2Rvd25sb2FkPVozbHdaRFJpT1cxb1kzbHcmY3J5cHQ9YmQzNTM4MWZmMDZjMmUwYWE4NTg5YjM4MWQ1NzhlMmVkZjdjZDY1ZTNkMTRjNzk2OTZjYWM0ZGVkNzJhOGFhNQ==";
var bedbfdefdbed="gypd4b9mhcyp/";
var caaaaabf="e75d81e8583ac115d3976b44b0a7c85c";
var cffcbfacbafd="cd386b6eeb0da44bc6dfdf24674e5d7b";
var ddcecdffddce="dHViZWxvYWQuY28=";
var dddebaea="124594";
var ebddecbefbeb="IZjdRjkOzZ3lwZDRiOW1oY3lwPoksj578H";
var fbffcdbc="AOsI758RaZ3lwZDRiOW1oY3lwBr74Aa";
var typeplayer="embed"; var vidconfig = {"id":"gypd4b9mhcyp","cors":"https://thumb.highdeliveryscdn.com/remotesrt/","showtitle":"","subload":false,"subsize":false,"logo":""};

```

**Comment by kolekan** [comment]
OK here is the code i change that works for me
```
        source = re.search(r'var\s*acdbebdfdfbf\s*=\s*"([^"]+)', html)
        if source:
            headers.update({'Origin': rurl[:-1], 'verifypeer': 'false'})
            url = source.group(1).replace('Y2QzODZiNmVlYjBkYTQ0YmM2ZGZkZjI0Njc0ZTVkN2I', '')
            url = url.replace('ZGY3Y2Q2NWUzZDE0Yzc5Njk2Y2FjNGRlZDcyYThhYTU=', '')
            url = base64.b64decode(url).decode('utf-8')
            return url + helpers.append_headers(headers)

```

**Comment by shellc0de27** [comment]
Thanks for the info. Looks like we are getting different values for some reason. May need to re-design the resolver

**Comment by kolekan** [comment]
> @kolekan can you test this resolver for me? made some changes to it [tubeload.zip](https://github.com/Gujal00/ResolveURL/files/8248473/tubeload.zip)

Yes it works for me, hopefully for all....

**Comment by shellc0de27** [comment]
Awesome, thanks again for reporting 👍 
Just included the changes in this pull #49

**Comment by Gujal00** [comment]
@shellc0de27 @kolekan 
I just pushed a fix in https://github.com/Gujal00/ResolveURL/commit/4a1996f043e5394b01f8cc1ff14dba24191366f0 can you test it please
looks like @shellc0de27 raised a PR with the same!!!

**Comment by shellc0de27** [comment]
@Gujal00 yeah looks fine to me. But technically i was quicker 🤣 :)

**Comment by shellc0de27** [comment]
i will close mine

**Comment by Gujal00** [comment]
> i will close mine

Thanks, I didn't realize you were working on it and i got to coding the fix and pushed the changes and saw your PR later

**Comment by shellc0de27** [comment]
All good man 😃 Honestly, without referencing your previous work.....i would still have my thumb up my ass lmao
