### ISSUE TITLE
StreamSB new domain

### ISSUE THREAD

**Issue by dracosc22679** [Gujal00/ResolveURL#487]
moviesland.xyz
This is a new domain dor StreamSB :-)

**Comment by Gujal00** [comment]
it is not new and possibly going dead next week. Do you have any working embed using that domain?
```
moviesland.xyz
whois information
Expires On        2023-06-24
Registered On   2021-06-24
Updated On     2022-06-17
```

**Comment by Gujal00** [comment]
just post here

**Comment by Gujal00** [comment]
Chillx update in https://github.com/Gujal00/ResolveURL/commit/43d555a6d7e00f1b12c2a9213b297275f9dd1bae
