### ISSUE TITLE
streamingcommunity not work

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#496]
Hi Guys, every time some streamingcommunity link not work on kodi.
thi is the link: `https://streamingcommunity.codes/watch/1146?e=9386`

I attach part of log file
[streamingcommunity.txt](https://github.com/Gujal00/ResolveURL/files/11796765/streamingcommunity.txt)

**Comment by Gujal00** [comment]
From the logs ResolveURL resolved the stream and passed it to kodi correctly. Kodi FFMpeg then opes the m3u8 master corrctely, then picks up the appropriate resolution sstream from the master correctly and then when playing the stream hits into issue with decrypting the encrypted stream
`ffmpeg[0x1866f63f7d0]: [crypto] Unable to open resource: https://sc-a3-19.scws-content.net/hls/16/b/d2/bd2b3d16-5c6d-4512-bfc6-c16698c56b39/video/720p/0000-1000.ts`
Nothing can be done in ResolveURL for this, as you have provided a log snippet, dont know what version of Kodi you are using. Try may be Kodi 21 Alpha 2 and see if it plays. Kodi 21 comes with FFMpeg6 which is a lot more capable and may play these streams
