### ISSUE TITLE
neohd plugin

### ISSUE THREAD

**Issue by mbebe** [Gujal00/ResolveURL#510]
line 35 should be:
```r = re.search(r"var\s*playerConfig\s*=\s*({.+?})", html)```

instead of:
```r = re.search(r"var\s*playerConfig\s*=\s*([^;]+)", html)```

h*ttps://neohd.xyz/embed/o4ic-rta0wcsqz7

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/f6d4a201252e14dd4eb7fd75891fe4ad2e9e8b4d
