### ISSUE TITLE
New Hoster VidGuard

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#543]
Hello from Germany.

can you please create the vidguard resolver.

URLs: 
```
https://vgfplay.com/
https://moflix-stream.day/
https://vidguard.to/
```

Video URL:
```
https://moflix-stream.day/e/m7WJxgBwVd5BzeQ/The.Witcher.S03e06.German.Dl.1080P.Web.H264-Sauerkraut.mp4
```

**Comment by kasi45** [comment]
https://moflix-stream.day/e/j8lKQxYm87xDGYb

**Comment by Gujal00** [comment]
Added in https://github.com/Gujal00/ResolveURL/commit/0423a2770374818e66c5917e16876207adf084d8
