### ISSUE TITLE
Dood streams new url.

### ISSUE THREAD

**Issue by ctubb111** [Gujal00/ResolveURL#560]
Can you please assist with this in ResolveURL

**Comment by Gujal00** [comment]
what is the url?

**Comment by ctubb111** [comment]
https://doods.pro/d/

Thanks Gujal for all your hard work

**Comment by Gujal00** [comment]
that was already added in https://github.com/Gujal00/ResolveURL/commit/c76fb183ef8e51a87750884a5107e41d437009ed 3 days ago

**Comment by ctubb111** [comment]
Sorry it’s not working for me or anyone else. I’ll send an example full link

**Comment by ctubb111** [comment]
https://doods.pro/d/y2ruyhneitj1

**Comment by Gujal00** [comment]
Are you using the git version? just because it is added doesnt mean it will start working instantly for everyone using the ResolveURL released version

**Comment by ctubb111** [comment]
I’m using the latest version that was released

**Comment by Gujal00** [comment]
And that was before this fix

**Comment by ctubb111** [comment]
My repo pulls from you sir

**Comment by Gujal00** [comment]
Works fine with the current git
```
info <general>: SMR Link Tester: Playing Link: |https://doods.pro/d/y2ruyhneitj1|
info <general>: SMR Link Tester: Link Supported: |https://doods.pro/d/y2ruyhneitj1| Resolvers: DoodStream
info <general>: SMR Link Tester: Link Resolved: |https://doods.pro/d/y2ruyhneitj1|https://a309a.dood.video/u5kj6hi7z7elsdgge7ptwl2ellz2landxlqwqkhhay2ycpy745qcwnstwfoq/gsrittgmtw~UpKST7WepH?token=l2w324ekr4ylr9eb7dkpy3ps&expiry=1691708029394|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_4%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F13.1+Safari%2F605.1.15&Referer=https%3A%2F%2Fdoods.pro%2Fd%2Fy2ruyhneitj1|
```

**Comment by ctubb111** [comment]
Sorry to bother you not sure what’s going on have a good night

**Comment by Gujal00** [comment]
No Problems, was keen to get the new embed from you to see if anything was changed at dood end, but seems to okay which is a relief

**Comment by ctubb111** [comment]
Again thanks for all your work we all appreciate you I hope you hear that
often because it truly is
