### ISSUE TITLE
Streamingcommunity not work 

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#563]
Hi guys, maybe streamingcommunity change his player and now not work on kodi.

https://streamingcommunity.bet/watch/6508

If you can check, please.

**Comment by Gujal00** [comment]
It uses encrypted streams now, no issue making a resolver but unable to play them in Kodi.
The m3u8s have this
`#EXT-X-KEY:METHOD=AES-128,URI="/storage/enc.key",IV=0x43A6D967D5C17290D98322F5C8F6660B`

**Comment by Gujal00** [comment]
@doko-desuka Yes, I do have IA playback code in SMR Link tester and it is not playing it. May be have to try with Inputstream-FFMPEGDirect.
Anyway playback is not Resolveurl's problem. It is just going to return the stream_url to whatever addon called it
