### ISSUE TITLE
doodstream need fix

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#588]
`https://doods.pro/e/vi993zxz56la`

[dood.txt](https://github.com/Gujal00/ResolveURL/files/12477824/dood.txt)

**Comment by Gujal00** [comment]
Works fine
`SMR Link Tester: Link Resolved: |https://doods.pro/e/vi993zxz56la|https://op153ff.video-delivery.net/u5kjzzrgttelsdgge44tkia7cht33bc4q3j4bpphed7jzdazffze573cjsda/6baxpk1ka3~azX1wYfaVm?token=o3ei5y85pw886p07odtps7o3&expiry=1693428508561|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+17.1.2%29+AppleWebKit%2F800.6.25+%28KHTML%2C+like+Gecko%29+Version%2F17.2+Safari%2F605.1.15&Referer=https%3A%2F%2Fdoods.pro%2Fd%2Fvi993zxz56la|`

**Comment by bassemhelal18** [comment]
Its really wired the link working fine with me (pc) but in same pc using Kodi I got Video file not found error

**Comment by Gujal00** [comment]
That is a cloudflare challenge page, unfortunately cant bypass that
