### ISSUE TITLE
[FR] Waaw support

### ISSUE THREAD

**Issue by MrDini123** [Gujal00/ResolveURL#598]
Hey,

So I was wondering the other day why was waaw support dropped. It seems to be really popular on some sites. Then I took a closer look and now I understand why. There seems to be many things they utilize so you can't scrape from them. I have tried my best however and came up with the following garbage, test code: [plugin.video.waawtest-0.7.0.zip](https://github.com/Gujal00/ResolveURL/files/12566763/plugin.video.waawtest-0.7.0.zip)

Basically there is an image with a play button and you have to send some x,y coordinate back to the server where the play button is in order to get back the media. Since we already have a GUI thanks to Kodi, I came up with that simple dialog and it works fine on my PC, I can move the square using the arrow keys on the keyboard. Unfortunately I haven't found a way to support touch screen yet. Maybe someone with more experience on Kodi controls could help me out there.

But I am interested about your opinion. Do you think something like this could be implemented in ResolveURL? I could also make this a separate script addon and ResolveURL could depend on that...

I also saw some query strings with captcha mention, but I never encountered any so far.

**Comment by Gujal00** [comment]
Yes, that is a great idea.
The ResolveURL plugin will look similar to the youtube plugin script.module.resolveurl/lib/resolveurl/plugins/youtube.py
basically you need to allow a plugin call point some thing like plugin://plugin.video.waaw/play/?video_id={0} and then it will call and work with your plugin

**Comment by Diniboy1123** [comment]
Sounds good. So I assume you don't want to include this GUI thing natively in resolveurl. If we do the separate add-on path, the only question is the repository. Where should I upload it?

**Comment by MrDini123** [comment]
Sorry, I posted from the wrong account first.

Sounds good. So I assume you don't want to include this GUI thing natively in resolveurl. If we do the separate add-on path, the only question is the repository. Where should I upload it?

**Comment by Gujal00** [comment]
WIll see if this can be turned into functions inside resolveurl. Thanks for your initiative.

**Comment by Gujal00** [comment]
Thanks a lot for this @MrDini123 added to ResolveURL in https://github.com/Gujal00/ResolveURL/commit/92c789ab075e301c48d381a1d274515469af7ca6

**Comment by MrDini123** [comment]
This is awesome news, thank you so much for the excellent port. The only remark I may have is the b64decode of the image. I needed the ==== and the verify on False and even then it would fail to decode properly in some cases. Couldn't figure out why. On the website it works in all cases. I am guessing it has to do with padding and how Python does base64 decoding.

**Comment by Gujal00** [comment]
@MrDini123 the padding characters are a maximum of 2, so `==` is more than enough. I had to remove `Verify=False` as that is not supported on Python 2. I tried a couple of embeds that I could find multiple times on both Kodi 21Alpha3 and Kodi 18.,9 and it worked correctly.
Please test and let me know the embed url if you find something that doesn't play. Thanks
