### ISSUE TITLE
blogger don't work

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#60]
https://www.blogger.com/video.g?token=AD6v5dw8qI72k5Q5-SggcsEP849R_kNg4fmkTvrc6bn1G3su2pDYRFX-2ZLm08SlMaJhIWUmYmBlDu6jbs1hJa5LuFcecX9c3-TQ3tzvke4EXpMoeFyQxdHVgX9DT2Y2PdWRKDJZzjI

**Comment by Gujal00** [comment]
Google resolver has been broken for a long time due to google oauth requirements.
You have to install googledrive addon and enable it in resolveurl settings and then resolveurl will use googledrive addon to resolve
