### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by Bain122** [Gujal00/ResolveURL#601]
ResolveURL github not connecting to device under file management.  ResolveURL service has disappeared from devices.

**Comment by Gujal00** [comment]
Resolveurl was never presented as source that can be used under file managment. Any addon that needs it will install it automatically. 
What guide are you following?

**Comment by Bain122** [comment]
I run Team Crew addon, I also tried your GitHub URL as a file link and it was empty

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by Bain122** [comment]
It's finding the links but not playing any of them.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by Gujal00** [comment]
Sorry there is no filelink for ResolveURL, as it was never intended to be installed that way. If some addon is not playing links, please take it with the addon developers.
