### ISSUE TITLE
drop resolver

### ISSUE THREAD

**Issue by Peter3344** [Gujal00/ResolveURL#617]
can you fix drop download 

`https://drop.download/j6fzop2ypt9c`

thank you in advance

**Comment by Gujal00** [comment]
The resolver is fine and resolving correctly. Probably the servers are overloaded and timing out
`info <general>: SMR Link Tester: Link Resolved: |https://drop.download/j6fzop2ypt9c|https://s33.drop.download:182/d/mlc2fr5w4xcdvbi4z2q4rwyl3ewva5urams26q3mokiypyuj5ltccaun6xespap3lq42u5o7/Mission.Impossible.Dead.Reckoning.Part.One.2023.Cima4U.mp4|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Fdrop.download%2Fj6fzop2ypt9c&Origin=https%3A%2F%2Fdrop.download|`
