### ISSUE TITLE
Subtitles?

### ISSUE THREAD

**Issue by Kliker12345** [Gujal00/ResolveURL#619]
I would like to know if it is possible to reproduce together with the film the translation that was added for example on filemoon? or any resolver?

**Comment by Gujal00** [comment]
No ResolveURL has no mechanism to look for or return subtitles.

**Comment by Kliker12345** [comment]
OK thank you. There is another problem with filemoon.. when playing a movie through Kodi, it skips scenes. and when I play the movie through the browser, it works normally.

**Comment by Kliker12345** [comment]
ok. i just ask beacuse only filemoon have problems in kodi.

**Comment by Kliker12345** [comment]
and clicknupload not working anymore.

**Comment by Gujal00** [comment]
Provide an clicknupload  embed that is not working and it can be looked

**Comment by Kliker12345** [comment]
they changed from clicknupload to clickndownload.org..resolver not working anymore

**Comment by Gujal00** [comment]
provide a working embed so that it can checked if it is the same site or a clone

**Comment by Kliker12345** [comment]
it is same site.. just now when you open url clicknupload.red or somthing else they go on clickndownload.org

**Comment by Gujal00** [comment]
@Kliker12345 do you have any filemoon embeds that have subtitles avaialable? I am working on adding subtitle support in feature/subtitles branch

**Comment by Kliker12345** [comment]
I will upload something and will send you

**Comment by Kliker12345** [comment]
https://filemoon.sx/d/669zmnayiqvk

**Comment by Gujal00** [comment]
@Kliker12345 filemoon is using streamed subtitles inside the m3u8 file, Like below
```
#EXTM3U

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs0",NAME="српски",LANGUAGE="sr",AUTOSELECT=YES,DEFAULT=YES,URI="https://be4235.rcr32.ams02.cdn112.com/hls2/01/04632/lang/srp/669zmnayiqvk_srp/index.m3u8?t=g7aQxBzLZ_RnDsojOjg9IdOl6XW6nnfghpDwKU08sh4&s=1703964462&e=43200&f=23164394&srv=26&asn=4771&sp=2000&fr=669zmnayiqvk"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1320459,RESOLUTION=1280x536,FRAME-RATE=24.390,CODECS="avc1.640029,mp4a.40.2",VIDEO-RANGE=SDR,SUBTITLES="subs0"
https://be4235.rcr32.ams02.cdn112.com/hls2/01/04632/669zmnayiqvk_h/index-v1-a1.m3u8?t=g7aQxBzLZ_RnDsojOjg9IdOl6XW6nnfghpDwKU08sh4&s=1703964462&e=43200&f=23164394&srv=26&asn=4771&sp=2000&fr=669zmnayiqvk

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=110694,RESOLUTION=1280x536,CODECS="avc1.640029",URI="https://be4235.rcr32.ams02.cdn112.com/hls2/01/04632/669zmnayiqvk_h/iframes-v1-a1.m3u8?t=g7aQxBzLZ_RnDsojOjg9IdOl6XW6nnfghpDwKU08sh4&s=1703964462&e=43200&f=23164394&srv=26&asn=4771&sp=2000&fr=669zmnayiqvk",VIDEO-RANGE=SDR
```

There is nothing to scrape for subtitles in the embed page, so resolveurl has nothing to do. If you play the stream returned by ResolveURL using Inputstream Adaptive, then Kodi will display subtitles as shown below
![screenshot00000](https://github.com/Gujal00/ResolveURL/assets/17394059/dabc630d-101b-4e95-873e-a0e14832e43d)

**Comment by Kliker12345** [comment]
Thank you for your hard work :) I not using filemoon anymore beacuse videos don't works very well in kodi from filemoon.
skiping scenes after few minutes watching.
