### ISSUE TITLE
youtube not work on kodi?

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#630]
all youtube link not work on kodi

test this 
https://www.youtube.com/watch?v=gggEKbFAJLk

**Comment by Gujal00** [comment]
ResolveURL simply passes the link to youtube addon. If it doesnt work, you have to update the youtube addon from the developers git. The youtube addon from kodi repo is old and doesnt work

```
info <general>: SMR Link Tester: Link Resolved: |https://www.youtube.com/watch?v=gggEKbFAJLk|plugin://plugin.video.youtube/play/?video_id=gggEKbFAJLk|
 info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.1) on O***** (Kodi-21.0) with Python 3.8.15
                                                   	Path: /play/
                                                   	Params: {'video_id': 'gggEKbFAJLk'}
```

![screenshot00000](https://github.com/Gujal00/ResolveURL/assets/17394059/9b05050b-408a-4039-8a3e-c23e5b9b5a3c)

**Comment by soter80** [comment]
> ResolveURL simply passes the link to youtube addon. If it doesnt work, you have to update the youtube addon from the developers git. The youtube addon from kodi repo is old and doesnt work
> 
> ```
> info <general>: SMR Link Tester: Link Resolved: |https://www.youtube.com/watch?v=gggEKbFAJLk|plugin://plugin.video.youtube/play/?video_id=gggEKbFAJLk|
> info <general>: [plugin.video.youtube] Running: YouTube (7.0.2.1) on O***** (Kodi-21.0) with Python 3.8.15
>               Path: /play/
>               Params: {'video_id': 'gggEKbFAJLk'}
> ```
> 
> ![screenshot00000](https://user-images.githubusercontent.com/17394059/278453439-9b05050b-408a-4039-8a3e-c23e5b9b5a3c.png)

ok guy, yopu can give me the developers git youtube link

**Comment by Gujal00** [comment]
youtube addon git
https://github.com/anxdpanic/plugin.video.youtube
