### ISSUE TITLE
possible resolver for vidsrc ?

### ISSUE THREAD

**Issue by pinoytracker** [Gujal00/ResolveURL#637]
Possible resolver !

`https://vidsrc.to/embed/movie/385687`

Thanks

**Comment by Gujal00** [comment]
Isn't that site taken down? I get a cloudflare can't reach message

**Comment by pinoytracker** [comment]
as of now its working on my side !

**Comment by Gujal00** [comment]
`vidsrc.to` is not a hoster, but is an embedder. you would need to scrape the actual embed and then pass it to ResolveUrl.

**Comment by pinoytracker** [comment]
thanks Gujal
