### ISSUE TITLE
UpBaam

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#649]
can you please check the pattern its not working 
can you check it again `https://cima120.uupbom.com/07uc2af5jtof`

also can you add this new domain 
`https://cdn1.upgobom.space/be5es6bo7km3/`

**Comment by Gujal00** [comment]
That embed uses a different method. Check with [this commit](https://github.com/Gujal00/ResolveURL/commit/5ddc12b183dc3ad7fa11048281ae86b1744c3107)

**Comment by bassemhelal18** [comment]
I tested all the domains with the pattern I push it before working fine

**Comment by bassemhelal18** [comment]
Thank you 🙏

**Comment by Gujal00** [comment]
`https://cdn1.upgobom.space/be5es6bo7km3/` is that a right embed? I am getting file not found. may be geo-restricted to Egypt?

**Comment by bassemhelal18** [comment]
Yes it's right

**Comment by Gujal00** [comment]
Added in https://github.com/Gujal00/ResolveURL/commit/650f3eb000c77c207638684ccc2ea09c0a30ed00
