### ISSUE TITLE
eplayvid.net

### ISSUE THREAD

**Issue by dober2** [Gujal00/ResolveURL#65]
Since the "entervideo.py" does nothing i wrote some code to resolve eplayvid.net.
Would be nice if you could add it.

```
import re
import random
import string
import time
from resolveurl.plugins.lib import helpers
from resolveurl import common
from resolveurl.resolver import ResolveUrl, ResolverError


class EnterVideoResolver(ResolveUrl):
    name = 'entervideo'
    domains = ['entervideo.net', 'eplayvid.com', 'eplayvid.net']
    pattern = r'(?://|\.)((?:entervideo|eplayvid)\.(?:com|net))/(?:watch/)?([0-9a-zA-Z]+)'
    
    def get_media_url(self, host, media_id):
        web_url = self.get_url(host, media_id)
        headers = {'User-Agent': common.RAND_UA,
                'Referer': 'https://{0}/'.format(host)}  
        html = self.net.http_GET(web_url, headers=headers).content
        
        match = re.search(r'''source src=\"(.*?)\"''', html, re.DOTALL)
        
        if match:
            return match.group(1)+ helpers.append_headers(headers)
        
        raise ResolverError('Video Link Not Found')

    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, template='http://eplayvid.net/watch/{media_id}')
```

**Comment by shellc0de27** [comment]
@dober2 What do you mean it does nothing? Works with all my embeds, Please provide an embed its not working with and we can take a look.
Also the current resolver is pretty much the same as your code above :)

**Comment by Gujal00** [comment]
> Since the "entervideo.py" does nothing i wrote some code to resolve eplayvid.net. Would be nice if you could add it.
> 
@dober2 entervideo.py is using GenericResolver class and works fine as is. 
As @shellc0de27 says if you have any embed that is not working, please provide it so that it can be analyzed.

**Comment by dober2** [comment]
I actually have no idea what the problem was. Works with the GenericResolver resolver now for the links i tested earlier. Kodi always gave me a bad request error i think.

**Comment by shellc0de27** [comment]
@dober2 Glad to hear its working for you
