### ISSUE TITLE
Struggling to get ResolveURL settings to display

### ISSUE THREAD

**Issue by CPritch** [Gujal00/ResolveURL#667]
Sorry to bother with opening an issue as I've tried most everything I can think of.

When I call the following in code nothing happens:

```python
def display_resolveurl_settings(self):
        resolveurl.display_settings()
```

I can see in my logs that resolveurl requests a bunch of settings that aren't found but I don't think that's an issue.
Is it down to the fact that I'm calling this from settings in my own addon with the following?

```xml
<setting label="ResolveURL" type="action" action="RunPlugin(plugin://plugin.video.aphrodite?action=authenticate&amp;service=resolveurl&amp;route=/settings)"/>
```

Any pointers would be much appreciated.

**Comment by Gujal00** [comment]
You can see that code is the same in plugin.video,smr_link_tester, however are you importing resolveurl at that point?

Calling from settings.xml also works in other addons like cumination which has this in its settings
```xml
<setting id="open_smr_settings" type="action" label="30027" enable="true" option="close" action="RunPlugin(plugin://plugin.video.cumination/?mode=main.smrSettings)" />
```

**Comment by CPritch** [comment]
Thank you so much, that was the secret sauce. I was missing the option="close" tag in my xml. Meant that the plugin was feeding settings back into the currently open settings window and failing.

All sorted now and cheers for the pointer on correct implementations.
