### ISSUE TITLE
What are test url? [Filemoon]

### ISSUE THREAD

**Issue by lavara123** [Gujal00/ResolveURL#672]
For example, what is the URL that will trigger this line? Which URL did you test it with?

https://github.com/Gujal00/ResolveURL/blob/master/script.module.resolveurl/lib/resolveurl/plugins/filemoon.py#L51

**Comment by Gujal00** [comment]
Report if something is not working. There may have been embeds which required that code at that point in time and may not be used anymore. The code was written by @shellc0de27 and he would have tested at the time.

**Comment by shellc0de27** [comment]
While i did the original resolver, i didn't make those changes. When you view the history you will see @Gujal00 did the code in @ ed739e7 and again in 4185e3c

**Comment by shellc0de27** [comment]
From what i remember, filemoon changed their code back to the original a couple days later hence the addition of the else statement in 4185e3c. So i assume that piece of code is not used anymore and may have been left there just in case they changed it back once again. You would have to confirm that with @Gujal00 though

**Comment by Gujal00** [comment]
@lavara123 Ah I remember now. Some the videos are allowed to be downloaded and if so will have `postData` in the unpacked code. I added it so that it will use the MP4 rather than the HLS provided for playback when available
