### ISSUE TITLE
send.cm

### ISSUE THREAD

**Issue by Kliker12345** [Gujal00/ResolveURL#677]
Hello can you check send.cm it's working but some files won't open. 

example: `https://send.cm/px5lki1ugv5l`

it's working on web but in kodi just start and exit. 

some files work in kodi but some just exit. 

Thanks

**Comment by Gujal00** [comment]
It looks like a load issue on the server, nothing wrong with the resolver. There is no timely response when the server is loaded and it just exits.
The embed you linked above, resolves and plays just fine
```
info <general>: SMR Link Tester: Playing Link: |https://send.cm/px5lki1ugv5l|
info <general>: SMR Link Tester: Link Supported: |https://send.cm/px5lki1ugv5l| Resolvers: Send
info <general>: SMR Link Tester: Link Resolved: |https://send.cm/px5lki1ugv5l|https://d1526.download-send.com/d/ozyvnvxy6gosj4l4oj6epapg32prz5a3fvco5cvfkvs362bi2ecnanveo5vsg2rwxjwjd3ml/video.mkv|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Fsend.cm%2F&Cookie=c_7hyj5tegwm4sd1%3Dpx5lki1ugv5l%3B+domain%3D.send.cm%3B+path%3D%2F%2Caff%3D198294%3B+domain%3D.send.cm%3B+path%3D%2F%3B+expires%3DFri%2C+05-Jan-2024+02%3A04%3A04+GMT%2C__cflb%3D0H28uocK7xWY9ysKQ1FuLgybRYw4v6DWLvCkwFEV5em%3B+SameSite%3DNone%3B+Secure%3B+path%3D%2F%3B+expires%3DFri%2C+22-Dec-23+02%3A34%3A04+GMT%3B+HttpOnly&Origin=https%3A%2F%2Fsend.cm|
```

**Comment by Kliker12345** [comment]
thanks

**Comment by Kliker12345** [comment]
Hey.. new problems with send.cm it's not working anymore. in kodi.log says video link not found i try different links and not working

Try this
https://send.cm/ngocbz4hcit0 

and they have another site https://media.cm/ 
can you add this in resolver. 

Thanks

**Comment by Gujal00** [comment]
@Kliker12345 send.cm fixed in https://github.com/Gujal00/ResolveURL/commit/8a267fd97d618e201e1e4320110bfa9890cdd44f

Can you provide an embed for media.cm, I suspect the code would be different for that site

**Comment by Kliker12345** [comment]
https://media.cm/16nkr66og76q

try this

**Comment by Gujal00** [comment]
It was added and released 2 days ago
