### ISSUE TITLE
[FR] Subtitle support

### ISSUE THREAD

**Issue by MrDini123** [Gujal00/ResolveURL#679]
Hi,

Certain providers like waaw have subtitle support which is not resolved at the moment by resolveurl since it doesn't have a way to return subtitles yet. Making an extra request to their site makes no sense if ResolveURL could theoretically already fetch them subs. I was thinking that we could introduce an extra boolean kwarg for the resolve method `subs=True` which could return a comma separated list of subtitle URLs followed by a `|` like how it is currently with the headers. So `http://media.url|Potentially=headers|http://subtitle.url,http://subtitle2.url` or so.

That way we don't break compatibility since that would only happen if the kwarg is passed.

Many of my users request this feature, because there are many fan-made subtitles available only that way. Or sometimes when there is no dub yet made and the content is in the original language, it also has supplied subs which we can't request at the moment.

**Comment by Gujal00** [comment]
The subs are usually loaded to subscene and opesubtitles and can be pulled during playback by the user once you have those subtitle addons installed.
Adding subtitle scraping is a major change and I dont understand the intricacies of the base code yet to go coding for such functionality. Will see what can be done

**Comment by vargalex** [comment]
Because of Kodi subtitle naming conventions, we need not only the subtitle URL, but the language too. You can find in the HTML source the language too (with errors of course) after the subtitle URL.

**Comment by Gujal00** [comment]
Yes. If at all this gets implemented, it should return a dict the way it is done for magnets
{'url': 'https://blah', subs: {'English': 'https://blah', 'French': 'https://blah' .......}}

**Comment by Gujal00** [comment]
Can you provide any sample embed that includes subs?

**Comment by MrDini123** [comment]
Sure. The one I originally tested my version of the captcha dialog on has some subs: `https://waaw.to/e/cwZV66C60UJs`. You can find the direct link to the srt directly in that page's source if you search for `.srt`.

**Comment by Gujal00** [comment]
@MrDini123 @vargalex 
Please test with feature/subtitles branch
You can test with SMRlink Tester by adding a link `https://waaw.to/e/cwZV66C60UJs$$subs`
For now subtitles feature is only added to waaw plugin

**Comment by vargalex** [comment]
@Gujal00 I have tested it with multiple linkd, works as expected. Thanks!

**Comment by MrDini123** [comment]
My apologies for the late reply. I reviewed both the code and have done some thorough testing on several links. All worked fine. I really like the outcome.

**Comment by Gujal00** [comment]
Add in 5.1.122 release
