### ISSUE TITLE
[FR] Optionally support custom DNS resolvers

### ISSUE THREAD

**Issue by MrDini123** [Gujal00/ResolveURL#680]
Hi,

I am struggling, because both my ISP and apparently also the [custom DNS provider](https://quad9.net/result?url=hqq.ac) seems to block certain domains used by stream providers. I usually just switch to `1.1.1.1` as my DNS for that time or add a hardcoded entry to these domains using `/etc/hosts`, but its not too convenient.

Then I came across [this repo](https://kodi-vstream.github.io/repo/), which seems to contain the dnspython module. I believe it would be pretty useful to have dnspython as an optional dependency within resolveurl and have an addon setting where I could specify my own resolver.

I could work on the implementation if you find this a decent idea. It would help a lot with my case when I can't resolve waaw or hqq on the `ac` subdomain. It would probably help a lot for people who live in countries where they block these providers using DNS as well.

**Comment by Gujal00** [comment]
you could easily replace`.ac` with `.to` before passing to resolveurl within your addon. ResolveURL uses urllib2 or urllib.request for the actual calls and it only supports proxy (https or socks). Not sure how dnspython can be used there.
