### ISSUE TITLE
streamgzzz

### ISSUE THREAD

**Issue by jewbmx** [Gujal00/ResolveURL#683]
Know how to resolve this url?
`https://streamgzzz.com/video/f2f1f0dc1a7bc1ffd57c5fb46cef2732`
Its found as a iframe on
`https://old.ssoap2day.to/watchmovies/the-family-plan`

I get the feeling it needs a little bit of work to play since the link plays on the soap site but errors elsewhere lol.

Also get the feeling this might be a site based resolve i need to do in my addon instead of it becoming a resolver but thought id check with a expert :)

**Comment by Gujal00** [comment]
Added the resolver, just pass the referer along with the embed to resolveurl for it to work like this
`https://streamgzzz.com/video/f2f1f0dc1a7bc1ffd57c5fb46cef2732$$https://old.ssoap2day.to/watchmovies/the-family-plan`

![screenshot00002](https://github.com/Gujal00/ResolveURL/assets/17394059/8ae3ca50-69ba-44d9-be9a-4eb3ab0db5e6)
