### ISSUE TITLE
More new hosts

### ISSUE THREAD

**Issue by Kliker12345** [Gujal00/ResolveURL#685]
I found more hosts you can check it

```
https://freedl.ink/
https://frdl.to/1oiyi2drt2om/S02E11.mkv.html
---------------------
https://flexy.stream/
https://flexy.stream/rt1oawl7lwt8
---------------------
https://prefiles.com/
https://prefiles.com/zsql4kzq0lvl/S02E11.mkv
---------------------
https://worlduploads.com/
https://worlduploads.com/ts9y267tgwul
---------------------
https://nelion.me/
https://nelion.me/iun3432ooo1v/S01E09.mkv.html
---------------------
https://maxstream.video/
https://maxstream.video/d14l7uzuhe3x
```

**Comment by Gujal00** [comment]
1. freedl can be done, but have to wait for 30 seconds before getting the link.
2. flexy can't be done as they use cloudflare captcha
3. prefiles can be done but they mention 60 seconds wait before getting the link
4. nelion cant be done as they have a download limit for free users
5. maxstream can't be done as they use cloudflare captcha

**Comment by Gujal00** [comment]
Added freedl, prefiles and worlduploads. The other three cannot be added due to cloudflare captcha

**Comment by Kliker12345** [comment]
I just found it that sites and send to you to check it .. if they ok you can add it :D if i find more i will send you :)
