### ISSUE TITLE
add viload

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#687]
add viload:

`https://doc.viload.org/watch/?v21#Nlo4Q2FCQXh6eFk3UFZqZ0k3dVhTcUppMU5CTTlVWFovVlJaV3ZweURTQWJIRmxKdjBEK0hRaU1yeHFRaDhXSGkycz0`

**Comment by Gujal00** [comment]
Unable to open the above link in browser, need the embed page linking to this hoster to inspect

**Comment by zoreu** [comment]
this javascript "https://doc.viload.org/js/app.min.js?v=16" rewrites the page with the id 'Nlo4Q2FCQXh6eFk3UFZqZ0k3dVhTcUppMU5CTTlVWFovVlJaV3ZweURTQWJIRmxKdjBEK0hRaU1yeHFRaDhXSGkycz0'

**Comment by Gujal00** [comment]
Provide a link that plays in a browser so that the logic can be followed for any headers, cookies requirement. Just providing stuff which doesn't play in a browser is of no use

**Comment by zoreu** [comment]
the link doesn't work in your browser? I don't understand why it works well here

**Comment by Gujal00** [comment]
yes doesnt work, probably restricted to your geo location
![viload](https://github.com/Gujal00/ResolveURL/assets/17394059/2ad64fa4-a275-4338-8857-217fa0f7915c)
