### ISSUE TITLE
I need help with a scrape in python

### ISSUE THREAD

**Issue by zoreu** [Gujal00/ResolveURL#695]
I'm putting together an addon and I can't find the m3u8 link on the website `https://webtor.io/`
here my magnet link: `magnet:?xt=urn:btih:363BC6C534B1430C6758318D196CCD61DB61B647&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce`

If you help me with scrape it will solve the torrent problem with the xbox

**Comment by Gujal00** [comment]
It is using `content-type: application/grpc-web+proto` for the posts and get which is all binary. Dont know how to do that in Python
