### ISSUE TITLE
Play private Vimeo videos on my addon

### ISSUE THREAD

**Issue by ponchofcult** [Gujal00/ResolveURL#704]
Hello, good day, I have some problems with the addon that I developed, it plays the videos of a page of a Japanese artist www.ariyasumomoka.jp to play the YouTube videos, I have no problem with: return resolveurl.resolve(url)
      
But for Vimeo I need to pass the referer in the headers and that way I can see the html of the site but not play the video, not even passing: 
resp = s.get(url, headers=headers) 
resolved = resolveurl.resolve(resp. url) 

I have even checked the script of the page and I have tried with an address that is similar to this: 
https://4vod-adaptive.akamaized.net/exp=1705961576~acl=%2Fc495dd73-62c7-4ed0-8d25-c8e29fc7a3db %2F%2A~hmac=309724ab08e02704d6f76fb19fc1951d34df95c7ee98365c1405a15521fdcfa6/c495dd73-62c7-4ed0-8d25-c8e29fc7a3db/parcel/video/9fc0f917.mp4 

or the audio:

https://4vod-adaptive.akamaized.net/exp=1705961576~acl=%2Fc495dd73-62c7-4ed0-8d25-c8e29fc7a3db%2F%2A~hmac=309724ab08e02704d6f76fb19fc1951d34df95c7ee98365c 1405a15521fdcfa6/c495dd73-62c7-4ed0-8d25-c8e29fc7a3db/parcel/audio /e722641c.mp4 

where only the image or audio is hosted (with some lag) but I have not had success either, can the video be played with audio in some way? If you check the videos are in tab MOVIES I'm testing with firt one, Thank you so much!

**Comment by Gujal00** [comment]
Works fine if you send the url as below to ResolveURL
`https://player.vimeo.com/video/903156870$$https://www.ariyasumomoka.jp/`
4K stream
![screenshot00000](https://github.com/Gujal00/ResolveURL/assets/17394059/d8221fcc-c68c-43e7-a2b1-5ea6fbaf6781)

**Comment by ponchofcult** [comment]
Wow, that's the way, thank you very much for that! To modify the quality, can I also add that option or would the Vimeo addon help with that?

**Comment by Gujal00** [comment]
ResolveURL usuallyreturns the file based on the setting `Automatically pick best quality`.

For HLS files such as vimeo ResolveURL returns the m3u8 as is and  you can control how you play that file in your addon, if you use Inputstream Adaptive, then it has its own settings on restricting quality
