### ISSUE TITLE
ds2play not work

### ISSUE THREAD

**Issue by demex2008** [Gujal00/ResolveURL#712]
hi can you see if you can fix ds2play and get the hoster started
Thanks

**Comment by MrDini123** [comment]
I am in no way responsible for this repository so this is just my personal experience, ds2play seems to be part of the dood clones and so it plays fine in Kodi for me. Did you check if the same title plays from browser? Maybe they deleted the content. I encountered a lot of deleted content there recently.

**Comment by demex2008** [comment]
To be precise, it's about freeomovie in cumination

**Comment by bassemhelal18** [comment]
I think in some countries there is a cloudflare Challenge 


[Isuue](https://github.com/Gujal00/ResolveURL/issues/588)

**Comment by Gujal00** [comment]
> To be precise, it's about freeomovie in cumination
@demex2008 
Yes ds2play sources sometimes are behind cflare in certain countries as @bassemhelal18 mentions above
I tried many from ds2play streams from that site and they play fine in my location
Just open the site in your browser and see if you get a cloudflare challenge page when you select ds2play source
