### ISSUE TITLE
Google drive not working

### ISSUE THREAD

**Issue by FalconEagleTest** [Gujal00/ResolveURL#721]
hi,
I am trying to get Google Drive links to work, I can see they are being resolved but not played.
i get :"Stream UrlOpen Failed: Url:"HTTP Code: 403 Msg:"
for example this one:
`https://drive.google.com/file/d/1zeZmnHX7DZ1MHMW8gglW0ACVVGGEe8m2`
thanks.

**Comment by Gujal00** [comment]
ResolveURL just passes the link to `plugin.googledrive`. So any issues you need to look into that addon.

The fallback code in ResolveURL is from 2014 and has not worked in years due to google changing the auth mechanism to OAuth2
