### ISSUE TITLE
uploadever.in not working windows

### ISSUE THREAD

**Issue by Kliker12345** [Gujal00/ResolveURL#723]
Hello i want first thanks to guja for hard work on this. Thanks man

Now `https://uploadever.in/a9e1dmfs2dpk` have problem on windows but androind work like userscloud before

thanks again :)

**Comment by Gujal00** [comment]
May have been a temporary issue. Works fine for me in Windows

```
info <general>: Starting Kodi (21.0-BETA3 (20.90.830) Git:20240221-480476cb59). Platform: Windows NT x86 64-bit
info <general>: Using Release Kodi x64
info <general>: Kodi compiled 2024-02-23 by MSVC 193431937 for Windows NT x86 64-bit version 10.0 (0x0A00000B)
info <general>: Running on Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.4046
info <general>: FFmpeg version/source: 6.0.1-Kodi
info <general>: SMR Link Tester: Link Resolved: |https://uploadever.in/a9e1dmfs2dpk|https://workerx3propconnectiontoawsa.instantbuzz.online/d/roolw6346uohr44kbvj5ogze244sawxqd55jnniyce5gbhcux3udludpk7xtpg2f77umqzdg/S04E02.mkv|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Origin=https%3A%2F%2Fuploadever.in&Referer=https%3A%2F%2Fuploadever.in%2Fa9e1dmfs2dpk|{}|
```

![screenshot00001](https://github.com/Gujal00/ResolveURL/assets/17394059/bb2ba6c7-9a78-4610-b177-c88b402b30e4)

**Comment by Kliker12345** [comment]
Somthing not ok. i try kodi 20.x and 21. beta 1 2 3 on windows and not working.. but on android phone it's working. but somthing is wrong for sure beacuse im uploader and i don't have any views on reports like before. 

Thanks

**Comment by Kliker12345** [comment]
And can you check userscloud somthing is happening won't open anything in kodi but via browser works fine

https://userscloud.com/xvr0ll5c160q

**Comment by Gujal00** [comment]
ResolveUrl resolves the stream correctly and passes it to kodi videoplayer.

Cant do much here as the streaming site `d174-163.userscloud.net` is slow and giving HTTP 503 messages. Even on browser it takes a while for the playback to start

**Comment by Kliker12345** [comment]
Ok thanks but can you check uploadever.in is not working

**Comment by Gujal00** [comment]
provide a debug log of it not working. As I said it works fine on my windows machine and I am unable to replicate your issue

**Comment by Kliker12345** [comment]
2024-03-03 12:31:14.703 T:14700   error <general>: ResolveURL: ResolverError Error - From: UploadEver Link: https://uploadever.in/o8m5la10nlm3: File Not Found or Removed
2024-03-03 12:31:14.706 T:14700   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resolveurl.resolver.ResolverError'>
                                                   Error Contents: File Not Found or Removed
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\plugin.video.strfilm\strfilm.py", line 172, in <module>
                                                       run_addon()
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\plugin.video.strfilm\strfilm.py", line 169, in run_addon
                                                       play_channel(id1, id2, id3)
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\plugin.video.strfilm\strfilm.py", line 144, in play_channel
                                                       playable_url = resolveurl.resolve(channel_url)
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\Nikola\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\uploadever.py", line 63, in get_media_url
                                                       raise ResolverError('File Not Found or Removed')
                                                   resolveurl.resolver.ResolverError: File Not Found or Removed
                                                   -->End of Python script error report<--
                                                   
                                                   
                                                   I tryed link in smr link tester and same result.

**Comment by Gujal00** [comment]
As I said before it may be that you are hitting cloudflare protection in your region and nothing can be done about it except use a VPN to another region

```
info <general>: SMR Link Tester: Playing Link: |https://uploadever.in/o8m5la10nlm3|
info <general>: SMR Link Tester: Link Supported: |https://uploadever.in/o8m5la10nlm3| Resolvers: UploadEver
info <general>: SMR Link Tester: Link Resolved: |https://uploadever.in/o8m5la10nlm3|https://speedx10gsecurityhighpmomdi.instantbuzz.online/d/rgobkf346uohr44kbrj5sgrm2ptll3gkjdgsni5io6rkarjrr5g5c5bxjwg2kbupgk2wtuol/Sisu2022.mkv|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Origin=https%3A%2F%2Fuploadever.in&Referer=https%3A%2F%2Fuploadever.in%2Ff%2Fgj6ytp-4k1v0lnvjsueb|{}|
```

![screenshot00000](https://github.com/Gujal00/ResolveURL/assets/17394059/e3bfb858-2d29-4c41-8978-e62ffa9b918c)

**Comment by Kliker12345** [comment]
i tested that. and works on vpn. But why i can open it via browser ?

**Comment by Gujal00** [comment]
> i tested that. and works on vpn. But why i can open it via browser ?

That is exactly the point of cloudflare bot protection, to allow browsers but stop scripts

**Comment by Gujal00** [comment]
ResolveURL's jonb is only to resolve the url and not playback. If it plays intermittently and not all it means is the server load on the streamer side
```
SMR Link Tester: Link Resolved: |https://send.cm/q3n3pg696pjm|https://d4130.download-send.com/d/izy5riez6gosj4l4hr7ensv5qgucxxyj4enxwy6bf3ryesvb22btfwkkdlwgdw7njw4tscal/S01E01.mkv|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Fsend.cm%2Fq3n3pg696pjm|{}|
```
