### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by herrdemo** [Gujal00/ResolveURL#728]
Hello guys, some streams from vk.com are buggy and don't work with Kodi.

error
<iframe src="https://vk.com/video_ext.php?oid=-122792749&id=456242041&hash=9358e6b9e633d7c1" width="640" height="360" frameborder="0" allowfullscreen="1" allow="autoplay ; encrypted-media; fullscreen; picture-in-picture"></iframe>

https://vk.com/video-122792749_456242041

ok
<iframe src="https://vk.com/video_ext.php?oid=-177948463&id=456239339&hash=d8fc54cd075cc0f1" width="640" height="360" frameborder="0" allowfullscreen="1" allow="autoplay ; encrypted-media; fullscreen; picture-in-picture"></iframe>

https://vk.com/video-177948463_456239339

If you can check it, please.

**Comment by Gujal00** [comment]
Not an issue with resolver as the second video cannot be opened even on a browser and displays `"Access restricted"`
Probably a geo-restriction
