### ISSUE TITLE
VidHide Resolver

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#731]
Hello from Germany

Can you create a new resolver for https://vidhide.com/?

Video Link:
https://moflix-stream.click/embed/wqi9ksytrg3l

**Comment by Gujal00** [comment]
> Hello from Germany
> 
> Can you create a new resolver for https://vidhide.com/?
> 
> Video Link: https://moflix-stream.click/embed/wqi9ksytrg3l

vidhide and moflix-stream.click is already part of the filelions resolver and the '/embed/' part was missing. updated filelions resolver to reflect the same.
