### ISSUE TITLE
febbox.com

### ISSUE THREAD

**Issue by shahaf1122** [Gujal00/ResolveURL#732]
hi.
is it possible to add Resolve febbox.com?

like this url:
`https://www.febbox.com/share/PItiXsDX`
i know it is possible because i saw websites using this website to stream in there website.

i found this maybe it will help.
`https://github.com/movie-web/providers/blob/f8a51200645ae9b1585972f59e972847ee1c5280/src/providers/embeds/febbox/mp4.ts`

i know that it is possible using hls.
you can see here: `https://github.com/Yonn1981/Repo/blob/49c020ec7cd03d9388491058b1f778e1eb2de7bb/repo/plugin.video.matrix/resources/sites/trash/showb.py#L151`
i try using hls but in high quality it is not possible to use hls and if it working is stuck.

thanks for your work!

**Comment by Gujal00** [comment]
That site is usually restricted to Egypt and I have no way of testing it while developing a resolver.
Can't do much as I dont have VPN to Egypt
