### ISSUE TITLE
Filemoon

### ISSUE THREAD

**Issue by dober2** [Gujal00/ResolveURL#733]
Hi,

filemoon probably have changed some stuff.

Example: 

`https://filemoon.sx/e/7xkrf836jk84`

**Comment by Gujal00** [comment]
Need the previous page which actually links to this. Basically it says
`<h1>This video cannot be watched under this domain</h1>` so probably has referrer requirement.

**Comment by dober2** [comment]
https://filmpalast.to/stream/parasyte-the-grey-s01e04

**Comment by Gujal00** [comment]
> `https://filmpalast.to/stream/parasyte-the-grey-s01e04`

Yes, it needs referer which SMR already supports for filemoon embeds. You need to pass the referer domain along with the embed `embed$$referer` as below
`https://filemoon.sx/e/7xkrf836jk84$$https://filmpalast.to/`

**Comment by dober2** [comment]
Thank you
