### ISSUE TITLE
voesx

### ISSUE THREAD

**Issue by Barclay6969** [Gujal00/ResolveURL#741]
Hello

Since last Update, voe.sx dues not work anymore. Can you fix it?

THX & BR
Barclay

**Comment by DWH-WFC** [comment]
Add new domain 'graceaddresscommunity.com'

https://graceaddresscommunity.com/e/cjl5uonwpvsw

**Comment by Gujal00** [comment]
> Hello
> 
> Since last Update, voe.sx dues not work anymore. Can you fix it?
> 
> THX & BR Barclay

@Barclay6969 voe.sx has a lot of domains, can you give me an embed which doesnt work so that it can be looked at

**Comment by Barclay6969** [comment]
Hello

it is the Domain https://graceaddresscommunity.com/e/cjl5uonwpvsw - But iaf i add it manually, voe does not work. No Error Message, just skipped in Kodi.

**Comment by Gujal00** [comment]
Did you check with the above commit fixing it?
