### ISSUE TITLE
voesx.py

### ISSUE THREAD

**Issue by Barclay6969** [Gujal00/ResolveURL#744]
Hello

Please add Domain to the voesx.py

shannonpersonalcost.com

Thx & Br
Barclay

**Comment by Gujal00** [comment]
completed in https://github.com/Gujal00/ResolveURL/commit/9bc18f92fa1500578bfa1faa5563fe45d97f22c2

**Comment by Barclay6969** [comment]
Thank you very much, IT works!!!
