### ISSUE TITLE
allvid

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#769]
`https://i.all-vid.autos/embed-ews25axgjo2w.html`

**Comment by Gujal00** [comment]
I can't open it, so probably geo-restricted, unfortunately cant do much
`<h2>Sorry, The video you requested doesn't exist or it has been deleted !</h2>`

**Comment by bassemhelal18** [comment]
Can you add this domain to allviid resolver it's the same only new domain

**Comment by Gujal00** [comment]
I cant test, but I have added it in https://github.com/Gujal00/ResolveURL/commit/fbffdce66828c19007e3bf76a9b5786ae62f6d1c
