### ISSUE TITLE
Voe

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#772]
Hello from Germany.
While browsing through films, I found pages to the left of Voe that cannot be played with the resolver but do run in the browser.

I read the link from kool.to.

`https://sethniceletter.com/access/eyJpdiI6ImVvaUdpcSs1TU1Ea3ZYbFBiTS9ZZUE9PSIsInZhbHVlIjoiRVF0NExwSG1oTi9LUHZ6MlZBVVZ0R2tPN1A0d204U0NaenAvZmVjeUxVcldrYjNGTExEZHkyeHhaSGRpRUxEWit6WnJ1bkxsUXBualBRckR4SnFZMVE9PSIsIm1hYyI6ImE4Mjk5NzgwMjUzNDg1MzIzM2UxYmI5YTBjNTJiMGZjNzI2NjNjYzc1ZjMzMDdkMGI1OWQ1ZjUwNTcyNDcxYzIiLCJ0YWciOiIifQ==?o=1`

The domain is already included, but the links from the website don't work in the resolver.

**Comment by Gujal00** [comment]
That is not a standard voe embed link. I will remove that domain then
