### ISSUE TITLE
Bowfile.com - New link structure

### ISSUE THREAD

**Issue by Heptamer** [Gujal00/ResolveURL#778]
Hi there,

I found out that the first example link I have provided was not the correct one. 

This is like it should be:
https://fs1.bowfile.com/no34/Rlktha.mp4?download_token=2b603cc609dee5b477dbbb65bb859943b015e86982a5f93c6696d7198de41d54

Would be great if you can update this Hoster :)

Thanks,
Hep

**Comment by Gujal00** [comment]
That is the final url that gets resolved, the token would be specific to your ip. the resolver is working fine as is. it is just that Kodi's Videoplayer uses a range call which is not supported by this hoster. Maybe it will work with external player
```
info <general>: SMR Link Tester: Playing Link: |https://bowfile.com/video/embed/no34/640x320/Rlktha.mp4|
info <general>: SMR Link Tester: Link Supported: |https://bowfile.com/video/embed/no34/640x320/Rlktha.mp4| Resolvers: BowFile
info <general>: SMR Link Tester: Link Resolved: |https://bowfile.com/video/embed/no34/640x320/Rlktha.mp4|https://fs1.bowfile.com/token/download/dl/no34/Rlktha.mp4?download_token=2c65631b749c89907ce0ce92944fb901bb4245ad07c87dcf6064f058c5e3b4c3|Referer=https%3A%2F%2Fbowfile.com%2Fno34&User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+17.1.2%29+AppleWebKit%2F800.6.25+%28KHTML%2C+like+Gecko%29+Version%2F17.2+Safari%2F605.1.15&Cookie=filehosting%3D091b014834e102407d6030c5792b4b10|{}|
```
