### ISSUE TITLE
gounlimited.to

### ISSUE THREAD

**Issue by teletcl** [Gujal00/ResolveURL#799]
I've found such address: `https://gounlimited.to/7hzl26tjrv87`
Don't know which plugin it could be added to.

**Comment by Gujal00** [comment]
That plugin was removed from resolveurl years ago as it is dead site. Good luck finding a working video from that site
`https://torrentfreak.com/pirate-streaming-hoster-go-unlimited-hacked-on-behalf-of-competitor-201016/`
