### ISSUE TITLE
Alldebrid resolving incorrect on season packs

### ISSUE THREAD

**Issue by theasguard** [Gujal00/ResolveURL#820]
Not sure if this is just something Im not doing right or if it's on the resolveurls end from my logs the requested query from my side is correct but what the resolver sends back is usually the last link from the all debrid sources. 
 is this something a person would have to look closer at with the resolver for all debrid? 
Or should I add a dialog pop-up for selecting the sources on my side
Or am I missing something else. 
I believe real debrid resolves season packs properly but it's been some time since I had an Rd account so Im not 100% sure, Sorry for being a pain in the ass

**Comment by Gujal00** [comment]
Did you follow the instructions in the Readme.md for getting back all the files?
`hmf = resolveurl.HostedMediaFile(magnet, return_all=True)`
If you didnt, it will always return the last playable file in the magnet list

**Comment by theasguard** [comment]
He

> Did you follow the instructions in the Readme.md for getting back all the files? `hmf = resolveurl.HostedMediaFile(magnet, return_all=True)` If you didnt, it will always return the last playable file in the magnet list

Hey thanks for the reply, I was looking at that before I made a comment actually, I think I sorted this now, after changing code I didn't clear the app of cached functions so I think that may of been my issue. Thanks again for replying I appreciate your work.
