### ISSUE TITLE
wolfstream.tv

### ISSUE THREAD

**Issue by demex2008** [Gujal00/ResolveURL#842]
can you fix wolfstream
mfg.

**Comment by Gujal00** [comment]
Do you have a working wolfstream embed?

**Comment by MrDini123** [comment]
I took a look on the site. It doesn't even load the stuff on the root domain. I am getting 504 Cloudflare gateway timeout errors after a while (once it timeouts). Several random "isitdown" websites also yield in the same result. It's probably down for everyone. You need to wait once its back.
