### ISSUE TITLE
vk.com

### ISSUE THREAD

**Issue by herrdemo** [Gujal00/ResolveURL#849]
@Gujal00 as attachment the update for the following URL types

https://vk.com/video-223902219_456239194
https://vk.com/video-122792749_456242046?list=ln-YXS9u57K48LhkU6C3X 

[vk.zip](https://github.com/user-attachments/files/16428442/vk.zip)

**Comment by Gujal00** [comment]
adapted in https://github.com/Gujal00/ResolveURL/commit/7a2807a5103a623def4c57621948a807a744f732
