### ISSUE TITLE
swiftload

### ISSUE THREAD

**Issue by demex2008** [Gujal00/ResolveURL#871]
Hello from Germany.
I have found a link  from the Filmpalst site

https://swiftload.io/v/8wbwz8lq0w

mfg.

**Comment by MrDini123** [comment]
Hi,

The provided link resolves just fine for me. However there hasn't been a ResolveURL release yet since @Gujal00 ported swiftload. So wait for the release or drop the swiftload.py file manually to your kodi folder.

**Comment by Gujal00** [comment]
Duplicate of #866  and #867
