### ISSUE TITLE
Another resolver

### ISSUE THREAD

**Issue by 1amnoob** [Gujal00/ResolveURL#890]
Hi,

Can you add this as well?
`https://drive.adramas.se/drive/M3lLTlV1QXdOTHVTUDNZVzJFMzhKZz09.html`

Thank you!

**Comment by Gujal00** [comment]
Pass the previous page which looks like `https://vb.adramas.se/v/p9im0U6NQs-3xviU280Elw.html` to ResolveURL and that will get the same stream url as the drive.adramas.se embed
