### ISSUE TITLE
please check furher.in url

### ISSUE THREAD

**Issue by teletcl** [Gujal00/ResolveURL#908]
Can You check `https://furher.in/e/v1dmt1vkg2ra` ?
In internet browser works but in Kodi doesn't.
`ResolveURL: ResolverError Error - From: FileMoon Link: https://furher.in/e/v1dmt1vkg2ra: Video not found`

**Comment by Gujal00** [comment]
Are you testing with commit https://github.com/Gujal00/ResolveURL/commit/496d2b914c8164ce75e899765de7eb8bd10b580a which has not been released yet?
`SMR Link Tester: Link Resolved: |https://furher.in/e/v1dmt1vkg2ra|https://be4242.rcr52.ams03.cdn112.com/hls2/01/06964/v1dmt1vkg2ra_x/master.m3u8?t=WHoBIlK3IpdRZmTvSLyyFvcXNm0APx-HfrH28hmFne8&s=1728858686&e=10800&f=34820024&srv=49&asn=4771&sp=5500&p=|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F117.0.8464.47+Safari%2F537.36+OPR%2F117.0.8464.47&Referer=https%3A%2F%2Fvy6482lz.xyz%2Fbdd%2Fv1dmt1vkg2ra&Origin=https%3A%2F%2Fvy6482lz.xyz&verifypeer=false|{}|`

**Comment by teletcl** [comment]
Works's now, thank for info.
