### ISSUE TITLE
wiki documentation for LivestreamsPro 3.0.0-alpha

### ISSUE THREAD

**Issue by enerdude** [Gujal00/ResolveURL#909]
Hi there

Sorry for posting the issue here, did not know where else to post. 
I eventually found your updated version of livestreamspro 3.00 that runs on recent Kodi versions using  Python 3.
https://github.com/Gujal00/gujal00.github.io

My problem is that the wiki is down (http://livestreamspro.pe.hu/wiki)
Can you please point me to a backup url or send me link to the documentation?

Thanks in advance

**Comment by Gujal00** [comment]
`https://toolsp.forumactif.com/` for support. It also has widgets linking to the wiki

**Comment by enerdude** [comment]
Wiki link there - http://lsprowiki.eu5.org/wiki/index.php?n=Main.HomePage

is also down.

By the way - is LSP 2.x.x python 2 xml files compatible with LSP 3.0.0alpha & f4mtester 4.1.0 (https://github.com/zoreu/plugin.video.f4mTester)?

**Comment by enerdude** [comment]
Hi I tested above xml with kodi 18.9 / livestreamspro 2.9.7 (Shani) and F4mtester 3.0.0 (Shani) and it works fine.

Do you know how I can make it work on Kodi 21 and which F4mtester should I use?

**Comment by Gujal00** [comment]
There is no f4mtester (Shani) for Kodi Matrix and above. Someone wrote f4mtester using inputstream.ffmpegdirect for Matrix and above but I dont think it supports HLSRetry and callback which was unique to Shani's version
The Wiki works fine, may be an issue in your region
![lspwiki](https://github.com/user-attachments/assets/529bc531-065f-428d-9aa3-6480aa14b138)

**Comment by enerdude** [comment]
Yes seems http://lsprowiki.eu5.org/wiki/index.php?n=Main.HomePage is up for me now.
I think the webhost where they host it was down earlier with my luck.

Thanks for your help!  Long live LSPRO 3.0!

**Comment by enerdude** [comment]
Just so you know, I found this: https://github.com/OnePlayHD/OneRepo/tree/master/matrix

https://github.com/OnePlayHD/OneRepo/blob/master/matrix/plugin.video.f4mTester/plugin.video.f4mTester-4.1.2.zip
and
https://github.com/OnePlayHD/OneRepo/blob/master/matrix/script.video.F4mProxy/script.video.F4mProxy-4.0.9.zip

is sort of the python 3 equivalent of Shani's addons.
The only big change is the callbackparameters that used to be
urlnew,cjnew=callbackmodule.f4mcallback(callbackparam, 1, inst, cookieJar , url, clientHeader)
is now
 urlnew,cjnew=callbackmodule.f4mcallback(callbackparam, referer, origin, cookie, 1, inst, cookieJar , url, clientHeader)

But it works fine in case you find anyone that want to use it.
