### ISSUE TITLE
Kinoger.re Resolver? or not?

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#911]
Hello from Germany.

I have a question about Kinoger.re. For a while Kinoger.re was with the provider Filemoon.sx. Kinoger.re has probably changed providers again. Unfortunately I couldn't find out where.

Is it possible to get the video links to work?

Thanks in advance

Video Links:
```
https://kinoger.re/#8vkvg
https://kinoger.re/#hukao
https://kinoger.re/#beiqq
https://kinoger.re/#hk5tf
```

**Comment by Gujal00** [comment]
There is too much obfuscated code in `https://kinoger.re/assets/index-CZ9UrXah.js` which is used for decrypting the api response. Would need help with someone skilled with JS

**Comment by Gujal00** [comment]
@DWH-WFC 
Can you please test with this commit https://github.com/Gujal00/ResolveURL/commit/c2654ec775073b4bc8270618ad0611a03e63b444

**Comment by DWH-WFC** [comment]
works fine thank you
