### ISSUE TITLE
filemoon need fix

### ISSUE THREAD

**Issue by bassemhelal18** [Gujal00/ResolveURL#920]
can you check this please 

`https://filemoon.sx/e/uikyc4phccus`

Thank you

**Comment by Gujal00** [comment]
looks like it needs the referer passed. Which site did you get that embed from?

**Comment by bassemhelal18** [comment]
I pass it but its didn't work too 
`Https://asd.quest`

The problem appears when request the iframe url

**Comment by Gujal00** [comment]
i need the full url of the web page in `asd.quest` where you found the embed. Reason is asd.quest is an aggregator, it then goes to a different embedder which then goes to the hoster. The referer url has to be the embedder, not `asd.quest`

**Comment by bassemhelal18** [comment]
`https://asd.quest/فيلم-the-outrun-2024-مترجم/`

And then press 
![image](https://github.com/user-attachments/assets/b736c821-a94d-4dd0-abc1-23b2d43be090)


But btw the link open in the browser without any refer

**Comment by Gujal00** [comment]
No, the filemoon links definitely not play on a browser. I tried filemoon embeds from other sites too. 
The above page which you referred to has other embeds and those play fine
```
<li data-link="https://w5.gamezone.cam/embed-embed-n0pj5ob20hkt.html" class="">
<li data-link="https://d0o0d.com/e/9577d752j0oh" class="">
<li data-link="https://vidmoly.to/embed-c23z3suunvf7.html" class="">
<li data-link="https://vtbe.to/embed-l1ocjd7t2drh.html" class="">
<li data-link="https://filemoon.sx/e/algct9z9hhl2" class="">
 <li data-link="https://voe.sx/e/tvwa1fedqvdp" class="">
```

Looks more like an issue on the filemoon site, which hopefully they fix soon

**Comment by bassemhelal18** [comment]
> 
> 
> 
> 
> `https://filemoon.sx/e/uikyc4phccus`
> 
> 
> 
> 

This URL play fine with me in browser 
![image](https://github.com/user-attachments/assets/43a37813-5e66-4a65-b4e8-3f9085389440)

I don't think it's a filemoon because same link in another addon 
But use it own request way working fine the problem is when the url frame found and get the request 
I got a 403 forbidden 
And a padding to disable MSIE and chrome friendly error

**Comment by bassemhelal18** [comment]
`2024-11-06 20:37:58.490 T:2864     info <general>: SMR Link Tester: Playing Link: |https://filemoon.sx/e/uikyc4phccus|
2024-11-06 20:37:58.576 T:2864     info <general>: SMR Link Tester: Link Supported: |https://filemoon.sx/e/uikyc4phccus| Resolvers: FileMoon
2024-11-06 20:37:59.763 T:2864     info <general>: SMR Link Tester: Link Resolved: |https://filemoon.sx/e/uikyc4phccus|https://be6721.rcr72.waw04.cdn112.com/hls2/01/07237/uikyc4phccus_x/master.m3u8?t=2xEqhLmtZvd7AfBSBWvCUA2uzbohgNkuJhH9UtiIno4&s=1730918279&e=10800&f=36186570&srv=30&asn=8452&sp=5500&p=|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+17.1.2%29+AppleWebKit%2F800.6.25+%28KHTML%2C+like+Gecko%29+Version%2F17.2+Safari%2F605.1.15&accept-language=en-US%2Cen%3Bq%3D0.9&Referer=https%3A%2F%2Ffile-zz40pd56-embed.com%2Fptsd%2Fuikyc4phccus&Origin=https%3A%2F%2Ffile-zz40pd56-embed.com&verifypeer=false|{}|`

**Comment by Gujal00** [comment]
Good find. I tried that embed on a browser and was getting 403, then I tried another embed from a different site which had the iframe and that was also causing 403 on the website itself. I still get the 403 on the browser for that above embed.
![filemoon](https://github.com/user-attachments/assets/cb6b64bf-819e-4710-a332-52b9d6e20724)

**Comment by bassemhelal18** [comment]
Thank you 🙏
