### ISSUE TITLE
TorBox Plugin

### ISSUE THREAD

**Issue by pikdum** [Gujal00/ResolveURL#932]
Any interest in adding TorBox as a debrid provider?

Currently working on a PR, might need some help wrapping things up though.

**Comment by pikdum** [comment]
PR should be good for a review. It's only implementing magnet link support.

**Comment by Gujal00** [comment]
Any plans for adding hosters support?

**Comment by pikdum** [comment]
Wasn't planning on it, but do other add-ons rely on that functionality a lot? Mine only uses ResolveURL for magnets, so not too familiar with it.

**Comment by pikdum** [comment]
Actually, not really sure what hosters TorBox even supports, lol.
I'll ask around to see if they have any documentation.

**Comment by Gujal00** [comment]
Sure, however I cant test it without a premium account. Do test it if you have one. I will merge your pr as is

**Comment by pikdum** [comment]
I've tested with my addon, but haven't tried any others yet.
Their servers are having issues right now anyways, though.

**Comment by Gujal00** [comment]
Hoster support would be nice to have as there are lot of non-english addons out there that use that. For now I will merge your PR, but please add hoster support when you can.

**Comment by pikdum** [comment]
Yeah, bit tricky to build without similar. Best we could probably do is hardcode the ones they explicitly support?

**Comment by Gujal00** [comment]
Yes, start with hard coded list of domains for now and ask them if they can provide a endpoint in the future.

**Comment by pikdum** [comment]
https://api.torbox.app/v1/api/webdl/hosters

**Comment by pikdum** [comment]
Also, can you re-open this? I'll have it close once hosters are added.

**Comment by Gujal00** [comment]
`https://turbobit.net/szcskov94wli.html` for testing

**Comment by pikdum** [comment]
I think #935 is ready to go now.
TorBox servers don't seem to be at 100% yet, but I was able to test both torrent and web download flows.

**Comment by pikdum** [comment]
Think things are in a good state to ship a new release?

**Comment by Gujal00** [comment]
> Think things are in a good state to ship a new release?

Done! 😃
