### ISSUE TITLE
streamembed

### ISSUE THREAD

**Issue by demex2008** [Gujal00/ResolveURL#940]
hello that's all I could find,

https://watch.gxplayer.xyz/watch?v=1C9SYEDV

https://watch.gxplayer.xyz/m3u8/3/48229fd6aa4328151e40bda429d8e182/master.txt?s=1&id=16769&cache=1

https://watch.gxplayer.xyz/stream/S3hDNWoyKzl0R1NhTVlFbVV1QXM2MWdBU3F6Qm1Bbm00aE00SXpYd3U3WHBsa2U5bVMrMEJIbmhDR2RDUzdHVU9HWEtVZkJGTWhVTk1JYjhIWWZyc2c9PQ==&id=16769

S3hDNWoyKzl0R1NhTVlFbVV1QXM2MWdBU3F6Qm1Bbm00aE00SXpYd3U3WHBsa2U5bVMrMEJIbmhDR2RDUzdHVU9HWEtVZkJGTWhVTk1JYjhIWWZyc2c9PQ==&id=16769.m3u8

mfg.

**Comment by Gujal00** [comment]
Why are you raising the same issue again, as it was already fixed and completed as mentioned in the earlier issue #938
