### ISSUE TITLE
Veev Resolver?

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#959]
Hello again from Germany.

I have a question, is this by any chance a new domain from Veev?

Video link:
`https://doods.to/e/2Hv4nVJxMyvGfg6OF9MmIOks42jk4UhiEcaXxBN`

**Comment by Gujal00** [comment]
yep it is as you can see `"Gujal00_loving_them_moves_buddy"` in the html page

**Comment by DWH-WFC** [comment]
- I'm tested in SMR Links from doods doesn't works. Is it the same for you?

**Comment by Gujal00** [comment]
it is very slow to start due to overloaded servers I presume. Keep trying at different times and it will work
