### ISSUE TITLE
file-upload.org fix

### ISSUE THREAD

**Issue by BalkanDzo** [Gujal00/ResolveURL#960]
Hello site have mainsteince and after back online links not working anymore meybe they changed smothing can you check

there is link

`https://www.file-upload.org/5lfyukt8qo5h`

and can you add new URL in send resolver

`https://send.now/aiwjxjldx1a6`

tnx

**Comment by Gujal00** [comment]
Cannot fix `file-upload .org` and `send.now` as they have put the site behind cloudflare captcha

**Comment by BalkanDzo** [comment]
im think they haved before and worked.. can you check it and try somthing?

**Comment by Gujal00** [comment]
ResolveURL wont work if cloudflare captcha is enabled. Just put the link on a browser and see if it is triggering cloudflare. It is triggering cloudflare for me in my region, so I cant do anything about it

**Comment by BalkanDzo** [comment]
thanks

**Comment by BalkanDzo** [comment]
I want inform you that File upload working.. they have mainstence yesterday and now working fine. but send not

**Comment by Gujal00** [comment]
send new domain was already added a couple of days ago in https://github.com/Gujal00/ResolveURL/commit/9b34d3f41841d03dee0ce74e97db96a48a592090
