### ISSUE TITLE
filemoon again

### ISSUE THREAD

**Issue by teletcl** [Gujal00/ResolveURL#961]
Can You check why for `https://filemoon.sx/e/0y68y7r0demv` resolver says: Video not found?

**Comment by androidrepublica** [comment]
Error Type: <class 'urllib.error.URLError'> : [SSL: NO_CIPHERS_AVAILABLE] no ciphers available

**Comment by Gujal00** [comment]
May be a regional issue. I am unable to replicate the issue as it works fine here on Windows Kodi
```
SMR Link Tester: Link Resolved: |https://filemoon.sx/e/0y68y7r0demv|https://be2719.rcr22.ams01.cdn255.com/hls2/02/05617/0y68y7r0demv_h/master.m3u8?t=YnjAtAAtRUDdJxmmnfGLLKE7dua0BiZyigOyQmtucPc&s=1734122627&e=10800&f=28089052&srv=26&asn=4771&sp=4000&p=|User-Agent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+17.1.2%29+AppleWebKit%2F800.6.25+%28KHTML%2C+like+Gecko%29+Version%2F17.2+Safari%2F605.1.15&accept-language=en-US%2Cen%3Bq%3D0.9&sec-fetch-dest=iframe&Referer=https%3A%2F%2Ffle-rvd0i9o8-moo.com%2Fptsd%2F0y68y7r0demv&Origin=https%3A%2F%2Ffle-rvd0i9o8-moo.com&verifypeer=false|{}|
```

**Comment by teletcl** [comment]
` SMR Link Tester: Version: |1.1.13| Queries: |{'mode': 'main'}|
 SMR Link Tester: Running on: Python 3.8.15 (default, Oct 17 2022, 02:39:57) [MSC v.1929 64 bit (AMD64)]|OpenSSL 1.1.1q  5 Jul 2022
 SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '13', '', 'resume:false']|
 SMR Link Tester: Version: |1.1.13| Queries: |{'mode': 'play_link', 'link': 'https://filemoon.sx/e/0y68y7r0demv'}|
 SMR Link Tester: Running on: Python 3.8.15 (default, Oct 17 2022, 02:39:57) [MSC v.1929 64 bit (AMD64)]|OpenSSL 1.1.1q  5 Jul 2022
 SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '14', '?mode=play_link&link=https%3A%2F%2Ffilemoon.sx%2Fe%2F0y68y7r0demv', 'resume:false']|
 SMR Link Tester: Playing Link: |https://filemoon.sx/e/0y68y7r0demv|
 SMR Link Tester: Link Supported: |https://filemoon.sx/e/0y68y7r0demv| Resolvers: FileMoon
 ResolveURL: ResolverError Error - From: FileMoon Link: https://filemoon.sx/e/0y68y7r0demv: Video not found`

**Comment by Gujal00** [comment]
As I said it could be a regional issue. Open the embed in a browser and see if it is going through cloudflare. If it is then it wont work in ResolveURL

**Comment by Gujal00** [comment]
Yes a browser will always play. Clear your browser cookies relating to filemoon, restart the browser and then put in the embed, if you see cloudflare captcha page then thats what ResolveURL is seeing and cannot proceed

**Comment by teletcl** [comment]
When I paste the url in Private mode in Firefox the video works.
But when I paste the url in Edge Browser, it tells me 403 - Forbidden
Maybe it's the same case as in this thread? https://github.com/Gujal00/ResolveURL/issues/920#issuecomment-2460697825

**Comment by Gujal00** [comment]
send new domain was already added a couple of days ago in https://github.com/Gujal00/ResolveURL/commit/9b34d3f41841d03dee0ce74e97db96a48a592090

**Comment by Gujal00** [comment]
yep, there is no facility in resolveurl to bypass DDoS protection by Cloudflare, DDoS-Guard, Sucuri, etc

**Comment by teletcl** [comment]
Doesn't work for me, but thanks for trying to help.

**Comment by teletcl** [comment]
Today, the link starts working in Kodi - strange.

**Comment by Gujal00** [comment]
The last release included https://github.com/Gujal00/ResolveURL/commit/b4e559f1696469d97940086c6a7c848777ebb636 and it may have started working for you
