### ISSUE TITLE
vidmoly not loading subtitle

### ISSUE THREAD

**Issue by AkosiKepweng** [Gujal00/ResolveURL#962]
hi, possible to check, subtiutle are not loading
`https://vidmoly.to/embed-blexwgok99lm.html`
thanks

**Comment by Gujal00** [comment]
Seems to be working fine
`SMR Link Tester: Link Resolved: |https://vidmoly.to/embed-blexwgok99lm.html$$subs|https://trst-1110-o.vmrest.space/hls/xqx2pxrog5okjiqbtfych6ix4kr5h55tkm7rrwye7,tocrfmgpvmgrb5n5cwq,24crfmgpvmfuhez7bea,.urlset/master.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Fvidmoly.net%2Fembed-blexwgok99lm.html&Sec-Fetch-Dest=iframe|{'English': 'https://srt.staticmoly.me/srt/01394/0c3cbkkzskpk_English.vtt', 'Portuguese': 'https://srt.staticmoly.me/srt/01394/0c3cbkkzskpk_Portuguese.vtt'}|`

![screenshot00000](https://github.com/user-attachments/assets/048305a2-ab76-41d1-84ce-a4b43d47898a)

**Comment by AkosiKepweng** [comment]
test with smr link tester version 1.1.13 , with resolveurl version 5.1.155, using kodi 21.1, subtitle are not loading, what would be the possible problem, Thanks

**Comment by AkosiKepweng** [comment]
`SMR Link Tester: Link Resolved: |https://vidmoly.to/embed-blexwgok99lm.html|https://verga-196.transitto.online/hls/xqx2pf6ng5okjiqbtf3chmkauci57twb5f2uq2jdn,2bgamremggksv4pckwq,ttgamremggg2jk3gsya,.urlset/master.m3u8|User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A109.0%29+Gecko%2F20100101+Firefox%2F117.0&Referer=https%3A%2F%2Fvidmoly.net%2Fembed-blexwgok99lm.html&Sec-Fetch-Dest=iframe|{}|`

**Comment by Gujal00** [comment]
You need to ask resolveurl to return subs. Smrlinktester will request subs and display them if you enter the embed into smrlinktester as `https://vidmoly.to/embed-blexwgok99lm.html$$subs`

**Comment by AkosiKepweng** [comment]
Thanks , working now
