### ISSUE TITLE
Remove items from search

### ISSUE THREAD

**Issue by jnojr** [Gujal00/ResolveURL#977]
Can we add a "three dot" option to remove individual search items?

I'll add things I want to watch in the future, series I'm currently watching, etc.  But if I mis-spell something, or search for and find something and then watch it, I'd like to remove that one item without clearing search history so i don't wind up with a growing number of things I don't care about.

**Comment by Gujal00** [comment]
huh?
What are you on about? There is no Search option in ResolveURL

**Comment by jnojr** [comment]
Ah, sorry, I assumed the search was part of that.  N/M...
